### ISSUE TITLE
allow to disable pageview tracking for certain providers (google analytics)

### ISSUE THREAD

**Issue by janmechtel** [segmentio/analytics.js#102]
We use a GA with a wordpress plugin and I want to keep it that way because they have more features.

I still like to use segment.io > Google Analytics for all the custom events we do via .track()

Therefore I need to disable that pageviews are sent to GA via segment.io

(Thinking about it this might leed to GA being loaded twice, any ideas? :-/)

**Comment by ma-zal** [comment]
In new Google Analytics UI, I cannot found, where i can disable initial GA "pageview". Please, provide me some detail, how to disable it in UI or by code.
