### ISSUE TITLE
Analytics.reset() should map to logout functions of integrations

### ISSUE THREAD

**Issue by calvinfo** [segmentio/analytics.js#128]
Should delete the cookies so you can alias without fear!

**Comment by simonepri** [comment]
@hankim813 What about the satus of this issue?

PS:
Mixpanel now has `mixpanel.reset();` function.

Currently this is what I'm using on user logout.
```
analytics.reset();
mixpanel.reset();
```

**Comment by hankim813** [comment]
cc @f2prateek

**Comment by f2prateek** [comment]
Tracking internally in https://segment.atlassian.net/browse/LIB-101
