### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Philmod** [segmentio/analytics.js#137]
Hey guys,

I get this error : 

```
Uncaught RangeError: Maximum call stack size exceeded
```

with the following text: 

```
_cio.push
(anonymous function)
_cio.push
(anonymous function)
_cio.push
(anonymous function)
_cio.push
(anonymous function)
_cio.push
...
```

Any idea how to fix that? It breaks all the javascript on the website...

**Comment by dhruska** [comment]
I know this is an old thread, but if anyone stumbles on this, I had a similar issue that I tracked down to an old Mixpanel script being referenced along with the Segment script.

**Comment by ChrisSki** [comment]
+1 to @dhruska

**Comment by neenhouse** [comment]
+1, same error

**Comment by shyrahnama** [comment]
For the record, I also had this error and made sure I didn't duplicate the snippet. Turns out analytics.js conflicts with date.js. Removing date.js got rid of this error.

**Comment by krulik** [comment]
Another for the record: it can also happen when you send a large object to `analytics.track` as there's a method which iterates through all of it's own properties.

**Comment by RuslanZavacky** [comment]
we experience same problem now, and it slows the whole UI drastically, maybe it worth to look into it, at least to give a meaningful error, where to look and what might be the problem?

**Comment by rawberg** [comment]
I would suggest **double and triple checking** the signature of your function calls. I ran into a similar issue when I inadvertently jumbled the order of parameters I was passing to the identify function.

**Comment by RuslanZavacky** [comment]
@rawberg thx for suggestion, we've actually found a problem, in Ember project, we've accidently passed whole model, and analytics.js started to clone a lot of internal dependencies going round and round :) Everything is fine now.

**Comment by krulik** [comment]
@RuslanZavacky Sounds exactly like what I've stumbled into ^.

**Comment by rbalicki2** [comment]
👍  this happened to me as well. I was accidentally passing an event a la `onClick={ this._onClickHandler.bind(this, true) }`, the parameters of which were being passed to `track`. `() => this._onClickHandler(true) }` solves it

**Comment by cmwall** [comment]
Chiming in to say that I got this error from a messed up snippet. 

The first line that initializes the analytics ended with a comma rather than a semicolon, causing the script to run over and over. 

Updating the snippet fixed it for me.

**Comment by DarrylD** [comment]
@cmwall mind pasting where, I'm too now having this issue

**Comment by cmwall** [comment]
@DarrylD 

https://segment.com/docs/sources/website/analytics.js/quickstart/#step-1-copy-the-snippet

**Comment by DarrylD** [comment]
@cmwall looked there, the first lines all end with semicolons, unless I'm missing something

**Comment by cmwall** [comment]
@DarrylD Sorry for the confusion but the error was on my end, not theirs. That was the snippet I used to fix the problem.
