### ISSUE TITLE
change intercom options to have a boolean for widget, string for widget selector

### ISSUE THREAD

**Issue by reinpk** [segmentio/analytics.js#230]
people get confused that they have to enter a default selector just to turn on the inbox. this way turning it on is just a checkbox and then they can choose to give a selector if they want to customize it

**Comment by morgs32** [comment]
Any chance you figured out how to change the activator dynamically? Such as - use the default one when it's suitable, but when there's a lot of content behind it in the bottom right hand part of the screen, switch to a custom activator button
