### ISSUE TITLE
consider automatic properties for trackLink

### ISSUE THREAD

**Issue by ianstormtaylor** [segmentio/analytics.js#238]
like `url` and `text`

**Comment by joachimmartin** [comment]
Yes- I added about 10-12 clickTrack calls to my site thinking it would send the href clicked on and now I've got to change from static properties to a callback just to get the href.  Text would be nice also.

**Comment by f2prateek** [comment]
Tracking in JIRA https://segment.atlassian.net/browse/LIB-147
