### ISSUE TITLE
Build version with only specific providers

### ISSUE THREAD

**Issue by philfreo** [segmentio/analytics.js#278]
Originally mentioned in #21:

> we actually want to provide a build tool + UI that will let you just check the providers you want and give you a custom minified version that only has the things you need.

Is this possible now?

I tried removing some lines from `component.js` and running `make analytics.js` but got some errors. Maybe it works if you also keep the list in `lib/integrations.js` in sync as well?  Would be nice if the list could be specified in a single file.

**Comment by MunGell** [comment]
I've implemented some kind of system that builds analytics.js with specific providers, it is in our fork here: https://github.com/Hexlet/analytics.js

And this is how we gonna use it: https://github.com/Hexlet/hexlet-analytics

I am currently working on tests to make sure everything works as expected (it works in browser, but fails "addIntegration" test). Any suggestions/comments would be much appreciated.

**Comment by francois2metz** [comment]
I started to create a web interface to customize, configure and build analytics.js. For now it's built for my own need, but check it out https://bytics.io/
