### ISSUE TITLE
Multiple mixpanel trackers

### ISSUE THREAD

**Issue by jpetey75** [segmentio/analytics.js#302]
With Mixpanel you can initialize multiple objects for different projects(tokens), i.e.:

mixpanel.init("YOUR_SECOND_PROJECT_TOKEN", {}, "p2");
mixpanel.p2.track("my event");

Would let us support multiple API keys in segment.io.

**Comment by tylercollier** [comment]
Is it possible to re-open this? It's been a while. Are the complexities worked out? I know this is not as easy as my hand waving here, but if analytics.js is properly modularized, it should be straight-forward. I'm guessing that one of the benefits of forcing the library to live at `window.analytics` is that it makes it simpler to explain to non-programmers, but if most such people just copy and paste the snippet you give them, 

Here's my scenario. I have many client websites that all want to see statistics for their own site. And I want to see statistics for all sites in aggregate. Furthermore, I will be keeping statistics of things I don't want my clients to see.

As it is, I'm glad I found this note on mixpanel. I'll have to go with them until Segment has similar capability. I like mixpanel, but I would prefer segment's help in keeping me out of vendor lock-in.

**Comment by ianstormtaylor** [comment]
Hey @tylercollier totally agree, and we want to cover it. It's coming up, but not in a timespan that I can guarantee a date or anything, sorry!

**Comment by tylercollier** [comment]
Ok thanks. I have the same request for the Wordpress plugin. Is there a place where I should make such a request?

**Comment by ianstormtaylor** [comment]
The WordPress plugin actually uses Analytics.js under the covers, so it would be solved with the same feature addition, so no need even!

**Comment by tylercollier** [comment]
It must do more than just include the Segment JS snippet. There is a lot of code in the wordpress plugin. All the options in the plugin like `exclude_custom_post_types` must be doing something on top of just including the snippet.
