### ISSUE TITLE
Non-subdomain cookie

### ISSUE THREAD

**Issue by tmcw** [segmentio/analytics.js#343]
Currently analytics.js sets cookies that apply to `.domain`, so they apply across subdomains:
https://github.com/segmentio/analytics.js/blob/master/lib/cookie.js#L35-L37

It's not clear if this is a user-customizable option - it would be great if it exposed methods to set cookie scope before setting cookies.

**Comment by andreisoare** [comment]
Is this still available? I can't find any documentation on how to customize the cookie domain and path for Analytics.js.

**Comment by digitalbase** [comment]
Just to be clear it's not.

If you're using this analytics.js (without segment.com) it's possible.
If you're using segment.com (either as paid or free subscription) this is not possible making all your cookies use the root domain 😤

**Comment by digitalbase** [comment]
There is another issue about this @ https://github.com/segmentio/analytics.js/issues/583
