### ISSUE TITLE
email tracking support

### ISSUE THREAD

**Issue by ivolo** [segmentio/analytics.js#349]
Do we have the ability to track email opens with segment.io? We need to add email tracking to our funnels. So far it looks like we will only be able to to track clicks from email using utm but what about email opens?

Mixpanel example https://mixpanel.com/docs/api-documentation/pixel-based-event-tracking .

**Comment by hankim813** [comment]
Can use our [Pixel API](https://segment.com/docs/libraries/pixel/)

**Comment by thellimist** [comment]
it'd be great if this functionality was included inside the library. Probably better if it was in NodeJS and other language libraries.
