### ISSUE TITLE
Using trackForm to track multiple events on the same form causes form submission to happen multiple times.

### ISSUE THREAD

**Issue by twoism-dev** [segmentio/analytics.js#355]
If I call trackForm on the same form (but with a different event), this causes the form to be submitted to the server multiple times - once per event.

```javascript
var form = $('form#new_user');
analytics.trackForm(form, 'event_1', {
  page_name : 'beta_invite_1'
}); 

analytics.trackForm(form, 'event_2', {
  page_name : 'beta_invite_1'
});
```

In the example above form#new_user will be submitted to the server twice. Both events fire correctly.

Many thanks.

**Comment by hankim813** [comment]
> If I call trackForm on the same form (but with a different event), this causes the form to be submitted to the server multiple times - once per event.

Why would anyone want to do this? 

> Also, this means trackForm can't be used with AJAX form submissions. The explicit form submission means you can't have a submit handler that uses preventDefault and then does an AJAX POST.

You should use normal `.track()` event and put that in the success callback of the ajax form. trackForm() is not meant for ajax form submissions :)

**Comment by twoism-dev** [comment]
Why is this closed, the original issue still stands - was the original issue fixed? (For non-ajax forms)

**Comment by hankim813** [comment]
I think this is not an issue but an expected behavior. Could you explain to me the use case for tracking the same form with the same properties but sending them as two different events?
