### ISSUE TITLE
Offline Caching

### ISSUE THREAD

**Issue by normanrz** [segmentio/analytics.js#358]
I looking for an analytics solution for a Cordova/Phonegap app. I cannot assume the user to be connected to the internet at all times, so I need some sort of caching when offline. Does this lib support that?

**Comment by flinn** [comment]
:+1:

**Comment by hereismass** [comment]
Hello, I am looking for the same thing for my webkit desktop app, which runs even if the user has no connection.

In the meantime I did a simple js wrapper over the HTTP API that does that : https://github.com/hereismass/osjs

**Comment by QuentinFchx** [comment]
Also the [Quick Start snippet](https://segment.com/docs/libraries/analytics.js/quickstart/#step-1-copy-the-snippet) does not handle cases where a web app is started without an internet connection.
We want to integrate with [the network information Cordova plugin](https://github.com/apache/cordova-plugin-network-information)

```js
if(window.navigator.connection && window.Connection && window.navigator.connection.type == window.Connection.NONE){
    document.addEventListener('online', function(){
        // Include Analytics.js script tag
    })
}
```

I understand that we don't especially want to add an overhead for everybody.
Do you think it would make sense to propose an alternative for Cordova apps with this additional logic, and update the documentation accordingly ?
I can do it myself, but if we could standardized it and make it available in the official doc for everybody...

**Comment by preexo** [comment]
+1 for this, would really make sense to make it part of the the package

**Comment by f2prateek** [comment]
Integrations are responsible for queueing events themselves - there's no way for the analytics library to be able to know that Mixpanel's SDK delivered the event while Amplitude's didn't (note that Amplitude's js library does it's own queueing as well for this reason).

As for Segment itself, we've added retries when sending data to Segment https://github.com/segment-integrations/analytics.js-integration-segmentio/pull/23. This is currently behind a flag and must be opted in, but we'll probably make it the default soon.
