### ISSUE TITLE
add .reset() method

### ISSUE THREAD

**Issue by ianstormtaylor** [segmentio/analytics.js#378]
That will clear any of the cached `id` and `traits` for `user` and `group`. This way people can reset if they don't want some of the previously recorded traits to be carried over. This would match our iOS and Android APIs.

cc @lancejpollard

**Comment by mxdubois** [comment]
Hey, it looks like `reset` was never added to the snippet over at https://segment.com/docs/libraries/analytics.js/quickstart/ . Seems like maybe it should be, but I could be wrong.
