### ISSUE TITLE
Duplicate loadScript in latest build?

### ISSUE THREAD

**Issue by chiplay** [segmentio/analytics.js#392]
Just happen to notice this today:

https://github.com/segmentio/analytics.js/blob/master/analytics.js#L6887
https://github.com/segmentio/analytics.js/blob/master/analytics.js#L9097

Guessing it was a build issue - just thought I'd let ya'll know.

**Comment by yields** [comment]
nope! that's a feature haha, just different load-script versions, we're still experimenting with reducing duplicates though!
