### ISSUE TITLE
Callbacks don't fire when analytics.page() is called with non-empty arguments.

### ISSUE THREAD

**Issue by fancyremarker** [segmentio/analytics.js#393]
I need to be able to set the `integrations` attribute in the `options` hash passed into `analytics.page()` (in order to exclude Customer.io from page tracking. However, when I do this, my `analytics.ready()` callbacks no longer fire. To be more clear, here are my snippets before and after adding the Customer.io exclusion:

#### Before: `analytics.ready()` callbacks fire correctly

```js
analytics.page();
```

#### After: `analytics.ready()` callbacks don't fire

```js
analytics.page(null, null, null, { integrations: { 'Customer.io' : false } });
```

My fix was to explicitly call all the callbacks, but this seems brittle, and is a bit annoying. Is there a better workaround for this? Thanks!

#### "Fix"

```js
analytics.page(null, null, null, 
  { integrations: { 'Customer.io' : false } },
  function() { _.each(window.analytics._callbacks.ready, function(callback) { callback(); }); }
});
```

**Comment by kanoshin** [comment]
Is this fix guarantee that all dependencies are loaded when callbacks are getting called?

**Comment by nhusher** [comment]
What's the status of this? I hit this bug today, and this ticket has been open for 19 months.

**Comment by hankim813** [comment]
Merging this into #409
