### ISSUE TITLE
add context for trackLink and trackForm

### ISSUE THREAD

**Issue by ianstormtaylor** [segmentio/analytics.js#396]
Right now you can't tell when certain events are `trackLink` or `trackForm` method calls later on when looking at the raw data, but we could add a specific piece of context, like so;

```js
var context = {
  library: {
    method: 'trackLink'
  }
};

analytics.track(event, properties, { context: context }, function(){
  ...
});
```

Which would then get mixed into the regular `context.library` stats, so that anyone can tell later in the logs where these calls are coming from.

cc @TheBecky

**Comment by hankim813** [comment]
triaged this internally ;-)
