### ISSUE TITLE
trackLink does not pass options through.

### ISSUE THREAD

**Issue by attack** [segmentio/analytics.js#403]
`track` takes `(event, properties, options, fn)` but `trackLink` only takes `(event, properties)`, so there is no way to pass through options.

It would be greatly appreciated if this attribute could be passed through.

**Comment by stevenmiller888** [comment]
+1 @yields @sperand-io

**Comment by tcassanego** [comment]
Definitely second it as well.  In the meantime, I've wrapped up the call to track in a click handler that sets a 300ms timeout and then changes pages.

**Comment by seantanly** [comment]
👍 +1

**Comment by SeyZ** [comment]
+1... we're now in 2017 :(

**Comment by heymanhn** [comment]
+1

**Comment by f2prateek** [comment]
Tracking internally https://segment.atlassian.net/browse/LIB-102

**Comment by f2prateek** [comment]
The change will be in a.js-core, closing this as a duplicate of https://github.com/segmentio/analytics.js-core/issues/41.
