### ISSUE TITLE
Add the ability to specify `ready` for individual integrations

### ISSUE THREAD

**Issue by calvinfo** [segmentio/analytics.js#409]
Something like:

``` js
analytics.ready('Mixpanel', function(){
  mixpanel.alias('foo');
});
```

so that users can have better control over which integrations they actually need to be `ready` in case one doesn't load.

**Comment by hadees** [comment]
+1 we've had some integrations that failed for some reason blocking all the other ones.

**Comment by kanoshin** [comment]
+1, it is sad, that this method is called only after ALL integrations are loaded. If I turn off some of them with page method, i still want to understand when other integrations are ready..

**Comment by dwkoogt** [comment]
+1

**Comment by mstockm** [comment]
+1

**Comment by TimeBomb** [comment]
+1
AdBlock breaks `analytics.ready` because we use the AdRoll integration. We have to create a custom interval to check when MixPanel is loaded, because we need to call `mixpanel.set_config`.

**Comment by cbledsoe** [comment]
+1

**Comment by elgreg** [comment]
+1

**Comment by f2prateek** [comment]
There's a PR for this in a.js-core. I'm closing this issue to track it there instead https://github.com/segmentio/analytics.js-core/pull/33.
