### ISSUE TITLE
Ability to add multiple instances of a single integration

### ISSUE THREAD

**Issue by jordanskole** [segmentio/analytics.js#410]
For example, we have 2 google analytics accounts we need to track, or we may want to add multiple instances of a single integration for redundancy during launches.

**Comment by yields** [comment]
that's definitely something we are working towards, i've been wanting to change the public api for a long time for something like:

```js
// `{...}` is just arbitrary configuration.
analytics.use(GoogleAnalytics({...}));
analytics.use(GoogleAnalytics({...}));
analytics.use(Amplitude({....}));
analytics.use(Amplitude({....}));
```

With the snippet the above would look like:

```js
analytics.add('google analytics', {...});
analytics.add('google analytics', {...});
```

cc @ianstormtaylor for some ideas :)

**Comment by yields** [comment]
actually the `GoogleAnalytics({...})` doesn't make sense when you have more than 10 integrations haha, so maybe just:

```js
analytics.integrate('Google Analytics', {...});
analytics.integrate('Google Analytics', {...});
```

**Comment by kmiyashiro** [comment]
Is there a workaround for doing this until it's officially supported?

**Comment by yagnik** [comment]
ping @yields I recently got hit by this problem too, any ideas on this ?

**Comment by yields** [comment]
it's something we want to do, don't know when exactly but it's in our backlog.
for now you could build a wrapper integration that supports multiple instances and `.use()` it in analytics.js.

**Comment by kmiyashiro** [comment]
@yields So, doing it manually with just `analytics.use(GoogleAnalytics({}))` would not work right now?

**Comment by drdee** [comment]
@yields is this still on your backlog? Any chance of bumping priority?

**Comment by yagnik** [comment]
@drdee did you try the strategy with a custom integration that calls other integrations ? I went down the rabbit hole but this would require a good amount of change internally.

**Comment by hankim813** [comment]
For GA, you can set multiple trackers as seen here: 

https://segment.com/docs/integrations/google-analytics/#multiple-trackers

I do not believe we will be moving forward with the strategy discussed here anymore so I'll close!
