### ISSUE TITLE
unbind event handlers

### ISSUE THREAD

**Issue by yields** [segmentio/analytics.js#412]
`trackLink, trackForm` bind `click` events, but there's no way ATM to unbind them since the callback is hidden, we can either add `.untrackLink, .untrackForm` or just return the callback.

i prefer we add `untrack*` since returning the callback will need major bump.

cc @ianstormtaylor

**Comment by busticated** [comment]
i realize this is an ancient issue but what was the ultimate resolution? i can't find anything spelling out how to `untrackLink/Form` in the docs. is there a way?

thanks in advance!
-matt
