### ISSUE TITLE
Doesn't load in chrome extension

### ISSUE THREAD

**Issue by hellyeah** [segmentio/analytics.js#416]
CSP in chrome extensions only allows https://

Analytics.js tries to load in http://
https://www.dropbox.com/s/u5wk87596udwojb/Screenshot%202014-11-09%2002.20.09.png?dl=0

For chrome extensions, you also have to allow https://www.google-analytics.com/analytics.js or else this error will occur:
https://www.dropbox.com/s/isuhr1twj842x13/Screenshot%202014-11-09%2002.20.55.png?dl=0

**Comment by yields** [comment]
you can checkout [daydream](https://github.com/segmentio/daydream#analytics) a chrome extension that uses analytics.js, it's not easy as it should be yet, but it's definitely something we want to improve.
