### ISSUE TITLE
pre-compile to better support bower

### ISSUE THREAD

**Issue by cvburgess** [segmentio/analytics.js#417]
Unless I'm missing something,  installing from bower leaves a lot to be desired because there is no usable analytics.js file to point to. Is there a good way to compile this on the fly or can we add a dist folder with a ready-to-use analytics.js file?

**Comment by yields** [comment]
last release we omitted analytics.js by accident, but i released 2.5.0 with analytics.js included, so you can use bower.

re-open if you're still seeing issues with installing :)
