### ISSUE TITLE
Running through a proxy/headless browser

### ISSUE THREAD

**Issue by cyberwombat** [segmentio/analytics.js#419]
Not an issue - but some brainstorm I am doing and would love to engage in a bit of discussion. My sites just cannot run all these analytics any longer - it just gets bogged down etc... so Ive been brainstorming on ways to somehow offset this by running analytics in some remote page - i.e on my main site just load a basic script that captures some info then sends it to a server which loads another page into a headless server with things like the user agent etc that came through the original script. What i send I suppose would depend (if I wanted to track each click on links clearly I need to send that but I think that can be done). Main issue I see is geo location since IP would differ though I wonder if some kind of xhr/socket trick could be used to get around that.  

Has there be thoughts towards this? I know there are issues I am not seeing at the moment and wondering if it's worth embarking upon.

Thanks for your time

**Comment by hankim813** [comment]
You could just move tracking to server side. Also all our integrations (except optimizely) are async so it shouldn't affect page load speed.
