### ISSUE TITLE
SecurityError in Safari when storage is disabled

### ISSUE THREAD

**Issue by dfreeman** [segmentio/analytics.js#421]
When a user has selected to block "cookies and website data" in Safari, attempting to access localStorage (annoyingly) throws a `SecurityError`.
Analytics.js appears to have an unprotected access to `window.localStorage` either in it or one of its dependencies that ends up triggering the global error handler in that scenario.

![image](https://cloud.githubusercontent.com/assets/108688/5580947/47621d16-9020-11e4-80c1-a713020fc6cf.png)

**Comment by yields** [comment]
hey @dfreeman, it looks like a lot of our dependencies do this, what's the expected behavior you think?
should it just wrap all access to localstorage with try/catch?

**Comment by dfreeman** [comment]
@yields In most cases (that I've seen, at least), libraries that make use of localstorage do some kind of initial check to see if the browser supports it at all, so usually the path to fixing this kind of problem is just wrapping that existing up-front check in a try/catch.

**Comment by yields** [comment]
I'll check with our deps maintainers and see if the try/catch route is feasible, i did this in yields/store (one of our deps) but it felt awkward weird thing to do haha.

**Comment by dfreeman** [comment]
Definitely a weird situation -- thanks for putting the time and effort in on this!
It's not a showstopper, but after scratching my head for a while wondering why these strange exceptions were coming in from time to time, I wanted to at least get the issues filed with our own upstream deps (like analytics.js) to get the ball rolling :)

**Comment by jonathanong** [comment]
:+1:
