### ISSUE TITLE
hash in pathname

### ISSUE THREAD

**Issue by stevenmiller888** [segmentio/analytics.js#428]
@yields When there is a hash in the pathname, for example,  `http://www.tuti.com/#/what-is-it/`, the event fired contains the path `/`. It should be `/#/what-is-it/`. Not sure if this is rectifiable, since `window.location.pathname` results in `/` too.

![screen shot 2015-02-10 at 9 47 24 am](https://cloud.githubusercontent.com/assets/7015626/6132780/e1a76048-b109-11e4-8541-f0f470c80e33.png)

**Comment by yields** [comment]
maybe we should send this as `hash: "#/what-is-it"`? i feel like `path` should be `window.location.pathname` cc @ianstormtaylor @DirtyAnalytics

**Comment by ianstormtaylor** [comment]
Agreed that just a single `#` hash shouldn't be reflected in the `path`. Although, we might make an exception for `#!` [hashbangs](http://www.adequatelygood.com/Thoughts-on-the-Hashbang.html) that are a browser-support workaround for updating the paths in older browsers?

**Comment by hugomn** [comment]
+1 for this issue. I'm using segment analytics in an angular application. I can see /#/pages in segment debugger, but they don't appear in Google Analytics. Can I help you somehow fixing this?

Best,

**Comment by stevenmiller888** [comment]
This is a problem in general for anyone using Angular, since it uses the "#" to denote differences in the path. Just something to think about

**Comment by yields** [comment]
i think if we include it in the path, we should always include it, so no hacky checks for `#!` since i think some frameworks do `#/` instead.

my only worry is that for the sites that use `#` properly, like link to images / headers etc.. it would show up as a different page potentially?

**Comment by stevenmiller888** [comment]
Can we maybe have a boolean that indicates that the "#" should be included?

For example,

```
analytics.page('Landing Page', {

**Comment by stevenmiller888** [comment]
Can we maybe have a boolean that indicates that the "#" should be included in the path?

For example,

```
analytics.page('Landing Page', {
  includeHashInPath: true
});
```

That's pretty ugly. Maybe there's a better solution along those lines though?

**Comment by yields** [comment]
```js
analytics.page('Page', {
  path: location.pathname + location.hash
});
```

^ you could do something like that too haha

**Comment by DirtyAnalytics** [comment]
Most people with the `/#/` URLs have been successful just self-populating the `path` like @yields said.

But this is probably becoming common enough to fix in a more programmatic way...

**Comment by ianstormtaylor** [comment]
+1 to @yields's solution there since it keeps a single code path. Don't really want to get into solving Angular's poor use of `popstate` if we don't have to, since like @yields said it adds complexity since `#` by default shouldn't be considered in the path. I think the current workaround is fine, but maybe just needs to be documented more prominently.

**Comment by ianstormtaylor** [comment]
If we end up adding a setting later, it will most likely be at the project-level, instead of individual calls. But that would be more of a last resort solution

**Comment by DirtyAnalytics** [comment]
Sounds good [here's an open issue](https://github.com/segmentio/site-docs/issues/372) we have to add an angular guide to the docs. I think @wcjohnson11 was thinking we could possibly make an angular plugin too.

**Comment by stevenmiller888** [comment]
Sounds good guys. Yeah we should probably add framework-specific (Angular, Meteor, etc.) docs to handle this.
