### ISSUE TITLE
escaping quotes in title

### ISSUE THREAD

**Issue by stevenmiller888** [segmentio/analytics.js#429]
If the title includes a quote, like:

 `<title>"washer" | Simple Energy Marketplace</title>`

Then we're not escaping the quotes:

![screen shot 2015-02-11 at 12 09 38 pm](https://cloud.githubusercontent.com/assets/7015626/6155290/e7c4fdcc-b1e6-11e4-9b4a-3b00cae1552d.png)

It shows up correctly in the debugger but gets an error back when it's sent out to the integrations. Should we fix this or encourage them to drop the quotes? @yields

**Comment by yields** [comment]
do we know which integrations error? it might make more sense to fix the integrations or something

**Comment by stevenmiller888** [comment]
Yeah I wasn't sure if it should be fixed on an a.js level or integrations level. It's happening with Iron.io.

**Comment by lambtron** [comment]
Any update on this? @yields  who would be the right person to confirm if this is the case?

I suspect this is going to be done on a.js, since it looks like (from @stevenmiller888's screenshot) that the request leaving the browser has the `"` inside of the double quotes.

Thoughts?

**Comment by yields** [comment]
I don't think this should be changed in a.js, the title is `<title>"washer" | Simple Energy Marketplace</title>`, so a.js does the right thing and picks up the title as is, and if we change that that would be a backwards incompatible change.

What we can do is fix iron.io integration to escape `"` in the title.

**Comment by owocki** [comment]
Hi there folks.  End-customer here.  Any questions, let me know.

**Comment by kevinSuttle** [comment]
I can open another issue, but this seems related:

I noticed that the quotes in `ajs_anonymous_id` aren't escaped either. [This slightly modified function](https://developer.mozilla.org/en-US/docs/Web/API/document/cookie#A_little_framework.3A_a_complete_cookies_reader.2Fwriter_with_full_unicode_support) from Mozilla did the trick.

```html
<script>
function getCookie(cookieName) {
  if (!cookieName) { return null; }
  return decodeURIComponent(document.cookie.replace(new RegExp("(?:(?:^|.*;)\\s*" + encodeURIComponent(cookieName).replace(/[\-\.\+\*]/g, "\\$&") + "\\s*\\=\\s*([^;]*).*$)|^.*$"), "$1")).replace(/['"]+/g, '') || null;
}
</script>
```

**Browser console**
```javascript
getCookie('ajs_anonymous_id')
"d8c973e6-c489-45d6-bedb-d6088d6d5099"
```

**Comment by yields** [comment]
@kevinSuttle we [`json.stringify`](https://github.com/segmentio/analytics.js/blob/master/lib/cookie.js#L77) stuff before storing them in cookies, you can just [`json.parse()`](https://github.com/segmentio/analytics.js/blob/master/lib/cookie.js#L96) them.

**Comment by kevinSuttle** [comment]
@yields good to know. Thanks!

**Comment by kevinSuttle** [comment]
Wait. Why are you stringifying quotation marks?

**Comment by jasonkarns** [comment]
@kevinSuttle 
```
JSON.stringify("foo")
""foo""
```

A guid string cannot be a bare word. It must be a string literal, thus, it must be wrapped in quotes.

**Comment by samkelleher** [comment]
Here I am 2 years later because I also ended up wondering Segment is wrapping the anonymous ID with quote marks for unclear reasons.  A GUID is a string so it's perfectly safe to store it in a cookie?

**Comment by jasonkarns** [comment]
@samkelleher 

The JSON representation of a string is `"some string"`. That is, the `"` quotes are part of the JSON payload. Ergo, they must be included in the value written to the cookie, just as the wrapping `{`/`}` braces would be if storing an object instead of a string.

IOW: 
This is valid JSON: `"d8c973e6-c489-45d6-bedb-d6088d6d5099"`.
This is not valid JSON: `d8c973e6-c489-45d6-bedb-d6088d6d5099` is not valid JSON.
