### ISSUE TITLE
trackForm will submit a form even if the event has been prevented

### ISSUE THREAD

**Issue by rsobers** [segmentio/analytics.js#431]
If a form submit event has been prevented by some other code (e.g., because client-side field validation failed), Segment's `trackForm` will still call `submit` and essentially override the prevention. As a result, the form will be POSTed _and_ the track calls will be executed even though the action didn't really happen.

I rolled my own version for now which checks `event.isDefaultPrevented()` and if it's true will bail out before submitting the form or calling `track`.

I realize this might not be the result everyone wants, just thought I'd raise the issue.

Note: KISSMetrics' `trackSubmit` is in between--if the event has been prevented, it won't submit the form, but it will track the event (causing event inflation). I think this is because they're not calling `prevent` but just inserting a delay.

**Comment by sperand-io** [comment]
@rsobers hey rob! thanks for the heads up on this!

just an fyi — @ianstormtaylor put our heads together here on how to respect the `defaultPrevented` case going forward, and should have an update in the next day or so

**Comment by rsobers** [comment]
Thanks for the update @sperand-io! 

One thing that's tricky, even with `defaultPrevented` is ensuring that the `trackForm` handling runs last of all the possible event handlers bound to the form submit click. I haven't dug too deep into how each of the browsers handle it, but from the bit I've read the handlers either fire in the order in which they are bound.

**Comment by rsobers** [comment]
Any updates on this @sperand-io?

HubSpot recently updated their form validation logic. Now, unfortunately, `event.isDefaultPrevented()` is true regardless of the validity of the form, so the method I suggested is no longer an option with them. I suspect it'll work for other popular landing page vendors still, though.

**Comment by benjaminhoffman** [comment]
any update on this?  I noticed trackForm fires even if form errors.

**Comment by snapswerve** [comment]
@sperand-io any update here? we're dealing with the same overreporting issue when tracking form submissions on instapage

**Comment by jonhilmarg** [comment]
Also having this issue, anyone found an easy solution?

**Comment by btruong** [comment]
@jonhilmarg I encountered the same issue when I started implementing client-side validation on our forms such as jquery validation lib.  I stumbled upon this post and implemented it and it proved to be very helpful. https://robsobers.com/tracking-form-submission-events/ Hope this helps.

**Comment by f2prateek** [comment]
Tracking internally in JIRA as well https://segment.atlassian.net/browse/LIB-148
