### ISSUE TITLE
userId overwritten with null during alias(userId)

### ISSUE THREAD

**Issue by dmitrygusev** [segmentio/analytics.js#434]
Hello,

I think there's a bug in Analytics.js, because I'm getting HTTP 400 while calling `alias(userId)`, and further Mixpanel's `alias` call uses wrong data for `previousId` (see below).

I have Analytics.js loader snippet on every page (I was using latest 3.0.1)

Here's what I'm doing:
 1. Navigate through web app to registration form
 2. Fill and submit the form
 3. Call `analytics.alias(userId)` as the first analytics call on a response page

Below is some debugger output attached to `onalias` in Analytics.js:
<img alt="onalias" src="https://cloud.githubusercontent.com/assets/76579/6278464/0df1783c-b8a8-11e4-8f3c-8c450d810781.png" width="600">

If I understand this right, `json` is just a clone of the `alias` object.

But while `alias` object has `from()` and `to()` methods, there are no `from` and `to` properties in the `json` object:

<img alt="mixpanel-from" src="https://cloud.githubusercontent.com/assets/76579/6279028/5e5289ba-b8ad-11e4-9a0e-ed5a40c6e988.png" width="150">

So when it comes to line 10642 (where `send` is invoked) I have `userId` overwritten with `null`:

<img alt="userId-null" src="https://cloud.githubusercontent.com/assets/76579/6278646/aad9fd12-b8a9-11e4-83d9-5a66c920ac78.png" width="450">

Hence the POST https://api.segment.io/v1/a 400 (Bad Request) error:
```json
{"message":"You must supply a `userId` string.","code":"invalid_request_error"}
```

I found one more thing that doesn't look right with the Mixpanel `alias()` call that's invoked soon after above method when Mixpanel integration enabled:

<img alt="mixpanel-alias" src="https://cloud.githubusercontent.com/assets/76579/6278952/757801b6-b8ac-11e4-9d53-416ab619d15c.png" width="600">

<img alt="mixpanel-from" src="https://cloud.githubusercontent.com/assets/76579/6279028/5e5289ba-b8ad-11e4-9a0e-ed5a40c6e988.png" width="150">

Here aliasing from `null` doesn't make any sense, because Mixpanel expects `mixpanel.get_distinct_id()`.

**Comment by yields** [comment]
@dmitrygusev just fixed + deployed -- thanks for the detailed report!

as for the mixpanel one, i'm not sure but i think that mixpanel will ignore the second argument if it's `null`?
can you open another issue in [segmentio/analytics.js-integrations](https://github.com/segmentio/analytics.js-integrations) for it?

**Comment by dmitrygusev** [comment]
@yields thanks for the fix, works good now.
Mixpanel integration seems working fine too.
