### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by cappslock** [segmentio/analytics.js#435]
I see that the GitHub project is at 2.6.6 and [npm](https://www.npmjs.com/package/analytics.js) is at 2.3.27. That's a lot of missing versions!

**Comment by eugene1g** [comment]
Yes please - the current NPM version is nearly 6 months old.

**Comment by nelix** [comment]
:+1:

**Comment by eugene1g** [comment]
It believe it's up to date now with https://github.com/segmentio/analytics.js/commit/337d83732382670de4a978b7a90a21d44f42aadf

**Comment by ndhoule** [comment]
Sorry for not replying here earlier—should be up to date now (and in the future).
