### ISSUE TITLE
User vs group vs identify

### ISSUE THREAD

**Issue by Aupajo** [segmentio/analytics.js#438]
In the docs, there is a section called [User & Group](https://segment.com/docs/libraries/analytics.js/#user-group), which states:

> Once Analytics.js loaded, you can retrieve information about the currently identified `user` or `group` like their id and traits.

This is the first time the page introduces the notion of the group, and nowhere does it document how to track a group, or what a group can be used for, or how it fits in with `identify`.

My main question is: how do I use user and group? From the source, it looks like I can do this:

```javascript
analytics.user().identify('user7');
analytics.group().identify('account21');
```

Does this supersede `analytics.identify()`? Does this play nicely with integrations?

Thanks in advance!

**Comment by hankim813** [comment]
Group call: https://segment.com/docs/libraries/analytics.js/#group
Identify call: https://segment.com/docs/libraries/analytics.js/#identify
