### ISSUE TITLE
Script causing IE to run slowly

### ISSUE THREAD

**Issue by domnet** [segmentio/analytics.js#444]
We're having an issue with the script running slowly in older versions of IE (8). When loading enroll.gas-south.com it stalls and points to Line 44 (Segment). All other browsers are working well. 
![segmentissue](https://cloud.githubusercontent.com/assets/5924840/6620935/fff03cc0-c8a9-11e4-969e-b61c72a817e4.PNG)

**Comment by stevenmiller888** [comment]
^ @yields Do we support IE8?

**Comment by yields** [comment]
> ^ @yields Do we support IE8?

[yup](https://travis-ci.org/segmentio/analytics.js/builds/53405571) we test on ie8 and other browsers.

> it stalls and points to Line 44 (Segment)

@domnet if you take a look at line 50 you'll see `new URL()`, can you remove it and see if it's causing that issue?

![screen shot 2015-03-12 at 6 31 21 pm](https://cloud.githubusercontent.com/assets/1661587/6622599/3c76e5e0-c8e6-11e4-823d-d5045176e743.png)

**Comment by domnet** [comment]
@yields Thanks. I just need to send the instructions to the developers. So to clarify you're suggesting remove the line 50 completely: "referrerPath: new URL(document.referrer).pathname,"

Thank you for your time!

**Comment by yields** [comment]
yup, there's no `URL` in older browsers, so you either have to replace it with something that works in older browsers or remove it if you don't care about `referrerPath`.

closing since it's not an issue with analytics.js.

**Comment by DirtyAnalytics** [comment]
@yields do you know a better way to get the `referrerPath` that will work more universally?

**Comment by yields** [comment]
> @yields do you know a better way to get the referrerPath that will work more universally?

yeah, analytics.js uses [component/url](https://github.com/component/url), you can use that or just do:

```js
var a = document.createElement('a');
a.href = 'https://referrer.com/foo/baz';
a.pathname; // => "/foo/baz"
```
