### ISSUE TITLE
Occasional trait storage failure

### ISSUE THREAD

**Issue by elliterate** [segmentio/analytics.js#447]
We're seeing occasional trait storage failure. We'll call `analytics.identify()` with an object of traits as the second argument, but our analytics vendors will not receive them. Subsequent calls to, e.g., `analytics.track()` will also result in requests to our analytics vendors without traits. Further, calls to `analytics.user().traits()` will return nothing.

We haven't been able to reproduce this on our machines, making debugging extremely difficult. And for the majority of users, it works perfectly. For those few users having the problem, there's no obvious correlation with operating system or browser or rendering engine, or any combination or version thereof.

We've been able to identify the issue because of remote logging from our JavaScript and from the data received by our analytics vendors (as seen in their respective UIs and verified by support representatives inspecting their server logs).

My current hypothesis is that initialization of the local storage adapter is failing for some reason (probably [here][1]), but that step is deep in a function closure, far from the prying eyes of my client-side code. (If someone can think of an easy way to add some custom debugging to that step, I'm all ears.)

[1]: https://github.com/segmentio/store.js/blob/master/store.js#L142

**Comment by hankim813** [comment]
If this is still an issue please reopen!
