### ISSUE TITLE
window.analytics conflicts with other libraries

### ISSUE THREAD

**Issue by trobertsonsf** [segmentio/analytics.js#452]
A million other libraries also rely on window.analytics. I need to be able to tell segment that it should attach itself to somewhere else when I bootstrap.  I'd like to tell segment that it should use window._segment  or whatever else I choose to avoid conflicts with other libraries.

**Comment by sirshannon** [comment]
yes, please. I can't use window.analytics due to other 3rd party code we cannot avoid using.

**Comment by sperand-io** [comment]
It's worth mentioning that if you're self-hosting the open-source version, you can use `noConflict` before initializing:

https://github.com/segmentio/analytics.js/blob/master/test/index.js#L25-L45

The Segment-hosted version *does* currently require you to use `window.analytics`.

**Comment by rawberg** [comment]
the previous link is 404-ing, is there updated example code for not attaching directly to window.analytics?

**Comment by sperand-io** [comment]
apologies — here it is: https://github.com/segmentio/analytics.js-core/blob/master/test/index.js#L25-L45

**Comment by ericodes** [comment]
thanks for sharing!

**Comment by chovy** [comment]
also getting 404, has this been resolved? I'm trying to load off cdn but I already have `windows.analytics` in used by another library.

**Comment by Steven5678231** [comment]
Same issue and the link didnt work, any suggestion or update on it?
