### ISSUE TITLE
leading slash on IE missing on {properties, context}.page.path

### ISSUE THREAD

**Issue by wcjohnson11** [segmentio/analytics.js#462]
This line in [page Defaults](https://github.com/segmentio/analytics.js/blob/master/lib/pageDefaults.js#L19) is collecting some path properties without the preceding '/', it looks like it might be happening in Internet Explorer.

**Comment by ndhoule** [comment]
Quick fix here is to update to `component/url@^0.2.0`. I'll have a stab at this in the morning.

**Comment by ndhoule** [comment]
Related PRs:

- [ ] https://github.com/segmentio/analytics.js/pull/463
- [ ] https://github.com/segmentio/analytics.js-integrations/pull/630 (removes `component/url` dependency)
- [ ] https://github.com/segmentio/analytics.js-integrations-private/pull/137
