### ISSUE TITLE
YUI compressor error on analytics.js

### ISSUE THREAD

**Issue by worthwhileindustries** [segmentio/analytics.js#471]
I am having an issue compressing analytics.js in the root folder using YUI. I understand it comes with a minified version but, it's part of our workflow to do it this way. 

There is a parse error somewhere as far as I can tell. Any ideas?

// I tried using an online compressor and it gets a parse error as well.
http://www.piliapp.com/minify/yui-compressor/

Error:

     [exec]     [COMPRESSOR ERROR] 14359:17:missing name after . operator

     [exec]     [COMPRESSOR ERROR] 1:0:Compilation produced 1 syntax errors.
     [exec] Exception in thread "main" org.mozilla.javascript.EvaluatorException: Compilation produced 1 syntax errors.
     [exec] 	at webAppBuilder.pkg.JavaScriptPackage$1.runtimeError(JavaScriptPackage.java:62)
     [exec] 	at org.mozilla.javascript.Parser.parse(Parser.java:392)
     [exec] 	at org.mozilla.javascript.Parser.parse(Parser.java:337)
     [exec] 	at com.yahoo.platform.yui.compressor.JavaScriptCompressor.parse(JavaScriptCompressor.java:312)
     [exec] 	at com.yahoo.platform.yui.compressor.JavaScriptCompressor.<init>(JavaScriptCompressor.java:533)
     [exec] 	at webAppBuilder.pkg.JavaScriptPackage.createMinifiedContents(JavaScriptPackage.java:40)
     [exec] 	at webAppBuilder.pkg.Package.getMinifiedContents(Package.java:163)
     [exec] 	at webAppBuilder.pkg.Package.writeOutput(Package.java:213)
     [exec] 	at webAppBuilder.Project.writeOutput(Project.java:78)
     [exec] 	at webAppBuilder.WebAppBuilder.main(WebAppBuilder.java:16)

**Comment by sperand-io** [comment]
@ndhoule @yields any idea here?

**Comment by yields** [comment]
@worthwhileindustries seems like yui doesn't like `is.boolean()`, for example this script fails with the same error as you get.

```js

var is = {
  boolean: function(v){
    return 'boolean' == typeof v;
  }
};

if (is.boolean(true)) {
  console.log('yes');
}
```

```bash
[ERROR] in test.js
  3:10:invalid property id
[ERROR] in test.js
  3:11:syntax error
[ERROR] in test.js
  5:3:syntax error
[ERROR] in test.js
  8:15:missing name after . operator
[ERROR] in test.js
  9:11:syntax error
[ERROR] in test.js
  10:1:syntax error
[ERROR] in test.js
  1:0:Compilation produced 6 syntax errors.
org.mozilla.javascript.EvaluatorException: Compilation produced 6 syntax errors.
	at com.yahoo.platform.yui.compressor.YUICompressor$1.runtimeError(YUICompressor.java:172)
	at org.mozilla.javascript.Parser.parse(Parser.java:396)
	at org.mozilla.javascript.Parser.parse(Parser.java:340)
	at com.yahoo.platform.yui.compressor.JavaScriptCompressor.parse(JavaScriptCompressor.java:315)
	at com.yahoo.platform.yui.compressor.JavaScriptCompressor.<init>(JavaScriptCompressor.java:536)
	at com.yahoo.platform.yui.compressor.YUICompressor.main(YUICompressor.java:147)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.yahoo.platform.yui.compressor.Bootstrap.main(Bootstrap.java:21)
```

if you change `boolean` to `bool` yui won't complain:

```js

var is = {
  bool: function(v){
    return 'boolean' == typeof v;
  }
};

if (is.bool(true)) {
  console.log('yes');
}
```

i think that's a yui bug? not sure.
