### ISSUE TITLE
Display page title for browser page tracking by default

### ISSUE THREAD

**Issue by kevinSuttle** [segmentio/analytics.js#472]
If you call `analytics.page( { name: pageTitle } )` in analytics-node, you get something like "MySite.com - Home" in your dashboard and debugger, as well as your integrations. 

If you use the same snippet in the browser, the page title is still part of the page tracking object, but the display defaults to the relative path.

**Comment by hankim813** [comment]
> If you call analytics.page( { name: pageTitle } ) in analytics-node, you get something like "MySite.com - Home" in your dashboard and debugger, as well as your integrations.

Since dashboard/debugger have changed since 2015, not sure if this is still an issue. Also different integrations ingest `.page()` calls differently so we'd need to know which specific integrations you are talking about :/
