### ISSUE TITLE
Shouldn't anonymousId be set to null after a valid user is identified? 

### ISSUE THREAD

**Issue by kevinSuttle** [segmentio/analytics.js#473]
In the cookie, `anonymousId` never goes away, even after a valid user has been identified. 
Whereas, the ajs_user_id cookie is null until a valid user has been passed to the identify call.

**Comment by f2prateek** [comment]
Why would you expect the anonymous user ID to be cleared?

**Comment by kevinSuttle** [comment]
Because it makes it easier confidently validate conditionals.

Example in Express
```javascript
if(req.cookies('anonymousId') === null) {
 // safely guarantee that the user has been created and referenceable in userId
}
```
I also expect the `alias` function to happen automatically during transition, so that while `anonymousId` has a value, `userId` gets aliased to it, then `anonymousId` is set to `null`, and the session tracking can be maintained from unauthenticated to authenticated.

**Comment by hankim813** [comment]
> if(req.cookies('anonymousId') === null) {
 // safely guarantee that the user has been created and referenceable in userId
}

There are several ways your `anonymousId` can change, such as calling `.reset()`, clearing browser cache, calling `.identify()` twice with different `userId`s so I don't think relying on the `anonymousId` is a reliable conditional.

Not only that if you are referring to "guaranteeing" that a given integration has the referenceable userId in their DB, not every tool even use our anonymousId so your code sample would not really be guaranteeing anything. Your `.identify()` call to a given integration might fail for any reason regardless of what the anonymousId might be.

Also our Warehouse product users often rely on anonymousId to be there for every call to do various attribution queries so this is not something we will ever change :/
