### ISSUE TITLE
Analytics is not a function.

### ISSUE THREAD

**Issue by schnie** [segmentio/analytics.js#476]
When I add the built version of analytics.js to an application, I get an `Analytics is not a function` error on [this line](https://github.com/segmentio/analytics.js/blob/master/lib/index.js#L16).

I believe it is because `analytics.js-core` has a [similar few lines](https://github.com/segmentio/analytics.js-core/blob/master/lib/index.js#L14) and exports the instantiated `Analytics` singleton, so when I get the error, `Analytics` is an object rather than a function.

**Comment by yagnik** [comment]
@schnie you had any luck with this ?

**Comment by schnie** [comment]
Fixed via 813f8d600cb00253f4d3c52862413d90807d8e94
