### ISSUE TITLE
analytics.js loading is blocking DOM

### ISSUE THREAD

**Issue by anedisi** [segmentio/analytics.js#477]
I have a standard snippet for loading analytics.js copyed from segment.io page, and have A/B testing on my signup page.
The A/B test is executed but the DOM is blocked (i cannot show/hide) elements till analytics is loaded on the page.
Am i doing something wrong ?

I have tested it in chrome and safari.
the only thing that i can do to not block my A/B test is to set the analytics snippet inside setTimeout 1000ms

**Comment by hankim813** [comment]
Hmm this should not be the case. Analytics.js is async and will not block any page rendering. Assuming this is no longer an issue will close but please reopen if it is!
