### ISSUE TITLE
why do I need segmentio when I can use analytics.js for free?

### ISSUE THREAD

**Issue by Maxhodges** [segmentio/analytics.js#484]
I'm curious why anyone would pay to use segment.io when you've open-sourced your business model by giving away analytis.js for free. 

Thanks
Max

**Comment by loganfuller** [comment]
Why does anyone use Amazon RDS when Postgres is free? Because then you don't have to do / maintain the integration yourself. Plus Segment provides a lot of value in data warehousing and event replay.
