### ISSUE TITLE
amplitude does not load

### ISSUE THREAD

**Issue by zowers** [segmentio/analytics.js#487]
we load scripts with `crossOrigin="anonymous"` as described in https://github.com/jrburke/requirejs/issues/687
```
    var requirejs_createNode = requirejs.createNode;
    requirejs.createNode = function createNodeAddCors( config, moduleName, url ) {
        var node = requirejs_createNode(config, moduleName, url);
        node.crossOrigin = "anonymous";
        return node;
```

But the https://d24n15hnbwhuhn.cloudfront.net/libs/amplitude-2.4.1-min.gz.js does not load
```
Script from origin 'https://d24n15hnbwhuhn.cloudfront.net' has been blocked from loading by Cross-Origin Resource Sharing policy:
No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://our-server.com' is therefore not allowed access.
```

Please avoid using global `window.require` or ensure the integration works with `crossOrigin="anonymous"`

**Comment by zowers** [comment]
the issue is still present, we have to work it around
```javascript
    var requirejs_createNode = requirejs.createNode;
    requirejs.createNode = function createNodeAddCors( config, moduleName, url ) {
        var node = requirejs_createNode(config, moduleName, url);
        if (url.indexOf("{{ scriptsRoot }}") == 0)
                node.crossOrigin = "anonymous";

        return node;
```

**Comment by hankim813** [comment]
@zowers is this still an issue using `//d24n15hnbwhuhn.cloudfront.net/libs/amplitude-2.12.1-min.gz.js`?

That is the current version of amplitude's js library we are using right now. If it's still an issue with that version I'll reopen!

**Comment by hankim813** [comment]
Also is this a problem isolated to using analytics.js? AKA if you use the amplitude library natively you don't have this issue? Just want to get more pieces to help point us in the right direction for debugging

**Comment by zowers** [comment]
I get
```
Script from origin 'https://d24n15hnbwhuhn.cloudfront.net' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.
errors.js:209 11:36:52:777 Name: Error
Message: Cannot load script

Details:
Modules: //d24n15hnbwhuhn.cloudfront.net/libs/amplitude-2.9.1-min.gz.js
Stack Trace:
 at Error: Cannot load script
 at Details:
 at Modules: //d24n15hnbwhuhn.cloudfront.net/libs/amplitude-2.9.1-min.gz.js
 at     at makeError (/components/requirejs/require.js:165:17)
 at     at HTMLScriptElement.context.onScriptError (/components/requirejs/require.js:1709:36)
```

didn't try to use amplitude myself

**Comment by hankim813** [comment]
@djih any idea on this? have you guys heard about this before or know where to look?

**Comment by djih** [comment]
@hankim813 : haven't heard of this before. we have limited support for requireJS and haven't fully tested it out ourselves. Sorry
