### ISSUE TITLE
Date string passed to `track` is modified

### ISSUE THREAD

**Issue by Leimi** [segmentio/analytics.js#490]
Hey Segment,

When sending a track event through `analytics.track`, date strings are modified by the API before sending data.

I pass:

```js
analytics.track("myEvent", {
  "myDate": "2015-10-30T14:10:00+0100"
});
```

And the API sends this to Segment and the integrations:

```js
{ "myDate": "2015-10-30T13:10:00.000Z" }
```

I don't want Segment to modify the timezone. This is not a "timestamp" field or anything specified in the Segment docs: I can put anything as the key (here, "myDate"), and the data still gets changed. I  think this shouldn't happen.
**Mobile APIs don't have this behavior**, so I guess this is a bug on the JS API? Or maybe I'm missing something.

Thanks for the help!

*At first I thought my issue was the same as #465 but I didn't read carefully. That let me see that we didn't have latest analytics.js available on the CDN and you fixed this problem recently but in the end it didn't change anything for this problem.*

**Comment by f2prateek** [comment]
This works as expected, if you send us a date looking string we'll clean it up. This lets us send the value to downstream integrations correctly. Rather than cleaning it up in each integration, we opted in to do at the top level.

We don't do this on mobile libraries for performance reasons.

**Comment by Leimi** [comment]
Thanks for the answer. This is kind of a bummer that this is expected. I don't understand why you have to modify the custom data I send. And the fact that the behavior is different depending on the APIs used is annoying too: when sending *the exact same custom data* via mobile, and via JS, it's not the *exact same custom data* that is, in the end, in the integrations.

I personnally think this shoudn't happen, but well, if you do, it would be great if this behavior was explained in the docs ;)

**Comment by f2prateek** [comment]
They're different platforms, so different behaviour is totally fine :)

Mabe I don't see the problem here — what's wrong about converting `"2015-10-30T14:10:00+0100"` to `"2015-10-30T13:10:00.000Z"`?

**Comment by Leimi** [comment]
Hey!

It's a problem for us because, while using standard format to ease the analytics process and data handling, we want to be able to go check for the dates with our human eyes and brain quickly… without having to think about converting the timezones to get the real date. If everything is set to UTC time, we have to check when was the data (summer? winter? etc.) and convert the time accordingly to get the "real" understandable time.

I guess I'll add another field with more "user friendly" date/time next to the ISO one!
