### ISSUE TITLE
HTTPS - Mixpanel Integration

### ISSUE THREAD

**Issue by ryanpager** [segmentio/analytics.js#491]
Is there a way to use https for mixpanel api requests rather than just standard 'http'. My mixpanel config contains the `secureCookie: true` and `crossSubdomainCookie: true` and it still does not seem to work.

Is there something im missing here, or is it actually a bug in Analytics.js?

**Comment by hankim813** [comment]
@ryanpager is this still an issue? These issues should go to the [mixpanel](https://github.com/segment-integrations/analytics.js-integration-mixpanel/blob/master/lib/index.js) repo in the future.

**Comment by schickling** [comment]
I'm having the same problem. Seems like it's fixed in the integration but not yet merged to this repo? (Sorry not sure about the workflow.)

How can I avoid this problem?
