### ISSUE TITLE
Overriding userId in .track() call

### ISSUE THREAD

**Issue by harsaharsa** [segmentio/analytics.js#495]
How to do this? I'd need to track events for several different users (one is an end user, another one is an admin user) from the same JS page. Is this possible via the JS API?

**Comment by hankim813** [comment]
This is not possible. If you want to change the `userId` inside a single `.track()` event, you need to call `.identify()` with the userId before. Thus this is not really best practice. If you want to track analytics in regards to your model, you should just send the end user id or admin user id as a property of the `.track()` event. Or better solution would be track the end user with analytics.js on your page and then send the `.track()` event for the admin via a server side library.
