### ISSUE TITLE
Can I load my segment key if I use the self-hosted analytics.js?

### ISSUE THREAD

**Issue by onlywei** [segmentio/analytics.js#498]
I don't want to include that big code snippet documented in the QuickStart into my HTML file. I'd rather load the UMD `analytics.js` module that I've installed with JSPM and load it using SystemJS.

If I load it this way, how can I tell `analytics.js` what my segment key is?

**Comment by josephspens** [comment]
I'm in the same situation. There are too many moving parts in my application, I need segment loaded synchronously and immediately, which means I need to package it with my application.

**Comment by rhys-vdw** [comment]
Same issue. Is this repository maintained? We're paying for this product...

**Comment by hankim813** [comment]
The open source version of analytics.js doesn't need/use a write key. You provide settings for all the providers directly.

Note that self hosting your own `analytics.js` as opposed to using the CDN means that you lost a big benefit of using Segment, which is on the fly updates to your analytics anytime you make changes. Self hosting means that you need to configure the settings for each integration directly and will need to redeploy your analytics.js any time you want to make any changes to your settings. 

In my honest opinion, it's always better/easier to just use the CDN.

> I'm in the same situation. There are too many moving parts in my application, I need segment loaded synchronously and immediately, which means I need to package it with my application.

This means that if any of your integrations' services are down, or have downtime or have slow servers, your app may be blocked which is probably not what you want :)
