### ISSUE TITLE
NetworkError from Maxthon browser

### ISSUE THREAD

**Issue by jchesterpivotal** [segmentio/analytics.js#501]
We use segment.io on a production application to track download events. 

We have a user who apparently uses the Maxthon browser. We get "NetworkError" exceptions sent to Honeybadger when they use Maxthon. The same user, after switching browsers and performing the same actions, does not cause the same errors to be emitted.

**Comment by jchesterpivotal** [comment]
This is still occurring.

**Comment by hankim813** [comment]
@jchesterpivotal can you list reproducible steps here if this is still an issue? What are the "actions" being performed?

**Comment by jchesterpivotal** [comment]
I wish I could, however it looks as though Honeybadger has dropped our copy of the original report. From the notes we kept at the time, it seems as though the user is attempting to download software from Pivotal Network (our downloads site). This sends an event to segment.io -- or tries to, then fails on a `NetworkError`.

The same user then switches to Firefox and successfully downloads that product.

Our code does nothing fancy -- literally sends a single event, `Clicked Download`, which then blows up somewhere in the segment.io code we pull in.

**Comment by hankim813** [comment]
And you've confirmed that without the `.track()` event, the user can successfully download using Maxthon?

**Comment by jchesterpivotal** [comment]
I can't say either way. What I *can* say is that the same user switches to Firefox and successfully downloads, meaning that the same tracking code is invoked in the same way.

This is why we suspect it's specific to Maxthon. We have not seen this error on any other browser.

**Comment by hankim813** [comment]
If you can reproduce it on your own computer or have multiple user reporting the same user with that browser, we can dig into this but right now we don't have much context here nor reproducible steps :/

I'll close the issue for now but if you do some isolated testing on your end with Maxthon such as removing the track call and checking the behavior. For all we know it could be any number of reasons ;)

Once those are ready just reopen this issue. Thanks!

**Comment by jchesterpivotal** [comment]
Given that this particular user just switches to Firefox, we'll accept your position that it's a known bug that won't be fixed.

**Comment by jchesterpivotal** [comment]
The same user came back, again with Maxthon, again with the same error.

```
{
  "DO_NOT_TRACK" => "1",
  "ON_LINE" => true,
  "COOKIE_ENABLED" => true,
  "VENDOR_SUB" => "",
  "VENDOR" => "Maxthon Asia Ltd.",
  "PRODUCT_SUB" => "20030107",
  "PRODUCT" => "Gecko",
  "PLATFORM" => "Win32",
  "LANGUAGE" => "zh-CN",
  "APP_VERSION" => "5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Maxthon/4.4.8.2000 Chrome/30.0.1599.101 Safari/537.36",
  "APP_NAME" => "Netscape",
  "APP_CODE_NAME" => "Mozilla",
  "HTTP_USER_AGENT" => "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Maxthon/4.4.8.2000 Chrome/30.0.1599.101 Safari/537.36",
  "HTTP_REFERER" => "[redacted]"
}
```

Backtrace

```
https://cdn.segment.io/analytics.js/v1/1upaeldra0/analytics.min.js:6 :in `i`
https://cdn.segment.io/analytics.js/v1/1upaeldra0/analytics.min.js:6 :in `e.w.send`
https://cdn.segment.io/analytics.js/v1/1upaeldra0/analytics.min.js:6 :in `e.w.ontrack`
https://cdn.segment.io/analytics.js/v1/1upaeldra0/analytics.min.js:6 :in `i.<anonymous>`
https://cdn.segment.io/analytics.js/v1/1upaeldra0/analytics.min.js:1 :in `i.n.emit`
https://cdn.segment.io/analytics.js/v1/1upaeldra0/analytics.min.js:1 :in `i.emit`
https://cdn.segment.io/analytics.js/v1/1upaeldra0/analytics.min.js:6 :in `i._invoke`
https://cdn.segment.io/analytics.js/v1/1upaeldra0/analytics.min.js:1 :in `i._invoke`
https://cdn.segment.io/analytics.js/v1/1upaeldra0/analytics.min.js:6 :in `i.track`
https://cdn.segment.io/analytics.js/v1/1upaeldra0/analytics.min.js:1 :in `i.track`
```
