### ISSUE TITLE
Track page views with Google Analytics and not with mixpanel 

### ISSUE THREAD

**Issue by elie222** [segmentio/analytics.js#502]
Hi, 

Is it currently possible to send a page event that only sends to GA and not to Mixpanel? 

I don't need to see page views in mixpanel. I really just want to use it for other events and people tracking. Is there a way to do this using analytics.js?

**Comment by loganfuller** [comment]
https://segment.com/docs/libraries/analytics.js/#page

Look at the `options` argument.

**Comment by hankim813** [comment]
@elie222 you can also use [selective integrations](https://segment.com/docs/libraries/analytics.js/#selecting-integrations) and add that option to your `.page()` calls.
