### ISSUE TITLE
.tracklink prevents external links from being loaded in an iframe

### ISSUE THREAD

**Issue by Hammadk** [segmentio/analytics.js#503]
We currently have a link in an iframe that's opened in the same window. It looks like:

``` html
<a target="_top" href="https://example.com">Example link</a>
```

This normally works but after tracking this link with `analytics.trackLink` we see the following error:

``` html
Refused to display 'https://example.com' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'.
```

This happens because analtyics.js intercepts the link and replaces the native action with [`window.location.href`](https://github.com/segmentio/analytics.js/blob/master/analytics.js#L515) which attempts to load `example.com` in the iframe, instead of the top window. Analytics.js should be replacing the native action with `top.location.href` instead which will load the link the top most window.

As a side note, the following works:

``` html
<a target="_blank" href="https://example.com">Example link</a>
```

**Comment by f2prateek** [comment]
If we were to set` top.location.href` instead - i feel like that could have other unintended consequences, no?

**Comment by f2prateek** [comment]
(tracking internally in JIRA as well https://segment.atlassian.net/browse/LIB-149)

**Comment by Hammadk** [comment]
I am not sure how it works internally, but I think it's safe to assume that links with `a target="_top"` should target `top.location.href`

**Comment by bdavies6086** [comment]
Hi @pooyaj 

I was wondering if there was any plan to implement this change? I am also experiencing the same issue and can see that at the moment there is no way to use trackLink using Anchor tags with _parent and _top target meta values

https://github.com/segmentio/analytics.js-core/blob/4f3035c5e959ea92d5c31a152211654242b23e00/lib/analytics.ts#L519

Thanks!
