### ISSUE TITLE
HubSpot adds __hstc, __hssc and __hsfp query params to all external URL, making them invalid

### ISSUE THREAD

**Issue by lolmaus** [segmentio/analytics.js#504]
Hi!

Here's a string I'm applying to a `href` attribute of a link:

    https://example.com/app#/tree?path=foo.bar

But when its rendered on the page, here's how it ends up looking:

    https://example.com/app&__hstc=181257784.ec3b8f50ceac6ae94ada7d99c135638e.1456488482298.1458396994219.1458561178659.71&__hssc=181257784.16.1458561178659&__hsfp=3702051802#/tree?path=foo.bar

Our backend filters by query params at this point, so the URL does not yield what it's supposed to.

How do I prevent those `__hstc`, `__hssc` and `__hsfp` query qarams from polluting all URLs? Note that I'm unable to prevent them from appearing at the frontend logic level, because at that level URLs are clean and get polluted after rendering by the HubSpot script injected by `segmentio/analytics.js`.

**Comment by syakovyn** [comment]
Hi!

We had a similar issue and fixed it by adding ? in front of #. So, for your case, it would be
`https://example.com/app?#/tree?path=foo.bar` and, after adding analytic parameters, it would appear as
`https://example.com/app?&__hstc=181257784.ec3b8f50ceac6ae94ada7d99c135638e.1456488482298.1458396994219.1458561178659.71&__hssc=181257784.16.1458561178659&__hsfp=3702051802#/tree?path=foo.bar`

That worked for us. Maybe, it will work for you too.

**Comment by hankim813** [comment]
@lolmaus are you still having this issue? 

This is an issue that should be opened over in the [segment-integrations/analytics.js-integration-hubspot repo](https://github.com/segment-integrations/analytics.js-integration-hubspot/blob/master/lib/index.js)

Could you open the issue there if still relevant? Thanks so much!
