### ISSUE TITLE
window.analytics.initialize is true even when window.mixpanel is uninitialized

### ISSUE THREAD

**Issue by TimeBomb** [segmentio/analytics.js#506]
When using Segment with the Mixpanel integration, we noticed that `window.analytics.initialize` was returning true despite `window.mixpanel` being uninitialized and set to an empty array (`[]`).

If the mixpanel integration is enabled, I would expect `window.analytics.initialize` to be false until `window.mixpanel` is initialized.

We are accessing window.mixpanel briefly right after we check if analytics are initialized, and this was causing quite the issue. We've solved it for the time being using this slightly hacky condition: `window.analytics.initialize && (!window.mixpanel || Object.prototype.toString.call(mixpanel) !== '[object Array]')` - wherein we check that mixpanel is either disabled (window.mixpanel being falsy) or that mixpanel is initialized (window.mixpanel not being an array).

**Comment by hankim813** [comment]
Hmm are you using `window.mixpanel` inside `.ready()`? ref: https://segment.com/docs/libraries/analytics.js/#ready

```js
analytics.ready(function(){
    window.mixpanel ..
});
```

**Comment by TimeBomb** [comment]
Ah, thanks for the tip. We actually weren't, Nevermind this issue then, the `ready` method is what we were looking for. Cheers.
