### ISSUE TITLE
Uncaught Error: cannot find module "bind-all"

### ISSUE THREAD

**Issue by elfeffe** [segmentio/analytics.js#513]
I'm using node 0.12.14 to build it
It builds, but I see this error on the website
`Uncaught Error: cannot find module "bind-all"`

And it does not initialize
What can I do?

**Comment by elfeffe** [comment]
I get some warnings on building
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated native-or-bluebird@1.2.0: 'native-or-bluebird' is deprecated. Please use 'any-promise' instead.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue



And 

npm WARN eslint-config-segment@1.0.18 requires a peer of eslint-plugin-react@^2.3.0 but none was installed.

├── UNMET PEER DEPENDENCY eslint-plugin-react@^2.3.0


Is that normal?

**Comment by rcline** [comment]
Hey @elfeffe!

I had the same issues stated last week.  The tldr; is that one of the dependancies pulled in the updated module that was no longer duojs capable, breaking Analytics.js `master` when re-running the build.

I have opened a PR to update this repo to include the latest changes to the core lib and integrations.  Let me know if it works for you!  PR #514

**Comment by elfeffe** [comment]
Yes, it works good!
I just have a warning
`npm WARN @segment/eslint-config@3.2.1 requires a peer of eslint-plugin-react@^4.0.0 but none was installed.`
But it works
Thank you

**Comment by rcline** [comment]
Awesome!

Ah, I am running NPM2 right now.
