### ISSUE TITLE
Track link redirection

### ISSUE THREAD

**Issue by Thomasvc1** [segmentio/analytics.js#518]
Hi, I've added link tracking to all my ankers and I've noticed that links that open a modal form using certain classes/attributes stopped opening them as a popup because the redirecting of analytics.js probably does not account for these.

Edit: I've fixed this by using the track function on links that open modal forms/blocks.

**Comment by f2prateek** [comment]
Is this related to #503 ?

**Comment by f2prateek** [comment]
(not the same symptoms, but seems to be due to the same underlying implementation)
