### ISSUE TITLE
analytics.ready() callback in a multi-server environment.

### ISSUE THREAD

**Issue by nratter** [segmentio/analytics.js#524]
We're using the Drift integration with Segment, but I'm trying to hide the chat icon that is loaded into the DOM by Drift in certain situations. I was able to accomplish this locally and in our staging environment (both are single-server environments) by using jquery inside the analytics.ready() callback that hides the appropriate div. However, when I tried this on production (in a multi-server environment), it didn't work. Any ideas?

I've also tried selective integrations in my code, but it looks like the DOM is being manipulated on initialization, not on page calls or identify calls. Any way to prevent this code from being loaded programmatically?

**Comment by f2prateek** [comment]
I believe this is because of https://github.com/segmentio/analytics.js-core/pull/33.

The issue is that a single integration failing to load can cause the ready callback to not be fired (which is done only when ALL integrations are loaded).
