### ISSUE TITLE
Trackform cancels redirection

### ISSUE THREAD

**Issue by andriigb** [segmentio/analytics.js#526]
After form submission, it has to redirect to another page:
 $("#formId").signUp({
                APIUrl : 'https://website.com/api/register_user',
                redirectUrl : 'staging'
            });

But, after I install track.form snippet in the footer, redirect is not working and page with form just reloads.

**Comment by f2prateek** [comment]
hey @andriigb , sorry for the delay. If you're still having this issue, could you write into support at https://segment.com/contact and someone from our team can help you out.
