### ISSUE TITLE
analytics.user() is not a function in analytics.ready() callback

### ISSUE THREAD

**Issue by evgenyrodionov** [segmentio/analytics.js#527]
Hi! I have this code in my `index.html`

```js
<script>
  !function(){var analytics=window.analytics=window.analytics||[];if(!analytics.initialize)if(analytics.invoked)window.console&&console.error&&console.error("Segment snippet included twice.");else{analytics.invoked=!0;analytics.methods=["trackSubmit","trackClick","trackLink","trackForm","pageview","identify","reset","group","track","ready","alias","debug","page","once","off","on"];analytics.factory=function(t){return function(){var e=Array.prototype.slice.call(arguments);e.unshift(t);analytics.push(e);return analytics}};for(var t=0;t<analytics.methods.length;t++){var e=analytics.methods[t];analytics[e]=analytics.factory(e)}analytics.load=function(t){var e=document.createElement("script");e.type="text/javascript";e.async=!0;e.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(e,n)};analytics.SNIPPET_VERSION="4.0.0";
    analytics.load("EcC0yl6WNunRcuZkDllhuKdl7fMHHrWQ");

    analytics.ready(function() {
      console.log(analytics.user());
    })
  }}();
</script>
```

When page loaded, I see error `analytics.user() is not a function`

![image](https://cloud.githubusercontent.com/assets/775692/20066234/ead08f88-a521-11e6-91da-7689a5d7fe0a.png)

Then I invoke manually from console and `analytics.user()` is presented.

![image](https://cloud.githubusercontent.com/assets/775692/20066254/faa02ffe-a521-11e6-9ca2-be107de5e6ca.png)

Why?

**Comment by evgenyrodionov** [comment]
Hey guys? @ianstormtaylor @calvinfo @yields

**Comment by yields** [comment]
@evgenyrodionov can you try:

```js
    analytics.ready(function() {
        console.log(window.analytics.user())
    });
```

**Comment by evgenyrodionov** [comment]
@yields it works, thanks. But is it ok? Why `window.analytics` and `analytics` is different?

**Comment by yields** [comment]
Inside the snippet's `<script>` scope, `analytics` is what the snippet defines.
Then `analytics.js` is loaded via another script tag, finally it is executed and will override `window.analytics`.

To use `analytics`, without `window.`, just use another script tag, like:

```html
<script>...snippet here :)...</script>

<script>
    analytics.ready(function() {
        console.log(analytics.user())
    });
</script>
```

**Comment by evgenyrodionov** [comment]
@yields I see, thank you. Probably it must be mentioned on [this page](https://segment.com/docs/sources/website/analytics.js/#user-group-information), what do you think?

**Comment by WesleyDRobinson** [comment]
https://github.com/segmentio/site-docs/commit/81370f8faa55f0e6ea9aa7123145360bca765a90
Cheers @evgenyrodionov

**Comment by pnedelko** [comment]
Seems like I was caught by the same thing.

I store the initial `analytics` object reference:
```js
const driver = window.analytics ? new SegmentDriver(window.analytics) : new MockDriver()
export default driver as AnalyticsDriver
```
The problem is that it just doesn't throw any error when you invoke some methods on this reference. It just doesn't produce any network requests. I was thinking I'm going crazy.

Guys, this really has to be documented! @WesleyDRobinson
