### ISSUE TITLE
Is open source version abandoned?

### ISSUE THREAD

**Issue by elfeffe** [segmentio/analytics.js#534]
Latest release is more than 1 year old.
Is this abandoned?

**Comment by f2prateek** [comment]
This is just a shell repo. It consists of https://github.com/segmentio/analytics.js-core + integrations. 
https://github.com/segmentio/analytics.js#contributing

As such it has no code to update.

a.js-core is extremely stable and hasn't need updates. Over 99% of the updates are in the integration specific repos https://github.com/segment-integrations?utf8=%E2%9C%93&q=analytics.js-integration&type=&language=
