### ISSUE TITLE
Replace Duo with Browserify

### ISSUE THREAD

**Issue by stephenmathieson** [segmentio/analytics.js#537]
I'm not sure how this hasn't happened yet, but we need to get rid of Duo here. I know @ndhoule did a lot of work here, but I'm not sure what's left.

/cc @segmentio/gateway

**Comment by f2prateek** [comment]
There was a plan to bring the work from a.js-private over to here https://github.com/segmentio/analytics.js/pull/514#issuecomment-231168232.

I don't know if that ever got done though.
