### ISSUE TITLE
Disabling Certain Properties on analytics.page

### ISSUE THREAD

**Issue by vhmth** [segmentio/analytics.js#538]
The call to `page` includes `url`, `referrer` and `path` by default. Sometimes the URL has sensitive information that we do not want to surface in integrations like Intercom. Is the proper way to exclude this information is to set these values in the `properties` hash to `null`? If so, I would move to get that added to the documentation.

![image](https://cloud.githubusercontent.com/assets/603426/23383051/81ea2742-fcf9-11e6-8a43-aac8d0c135aa.png)

**Comment by f2prateek** [comment]
Unfortunately, this isn't currently possible.

I think we could support this with middlewares. Tracking internally in JIRA https://segment.atlassian.net/browse/LIB-145.

**Comment by dabbeg** [comment]
You can override the default properties(url, referrer, search, ...) when calling page with passing an object as the second parameter of the page function.
https://segment.com/docs/sources/website/analytics.js/#default-properties

**Comment by pooyaj** [comment]
Middleware is no released, and can address this use-case: https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/#middleware
