### ISSUE TITLE
Analytics.prototype.track callback should wait on result and indicate status

### ISSUE THREAD

**Issue by benwiley4000** [segmentio/analytics.js#539]
The callback function sent to `Analytics.prototype.track` is pretty useless - it just fires after a timeout instead of waiting on the response status. In some cases we may want to wait on event tracking completion before, say, navigating to a different webpage.

**Comment by f2prateek** [comment]
What status should it wait on? 

There are multiple client side integrations, all of which may make a request. Each has its own behavior.

1. Most (if not all) don't even give us a callback to hook into.
2. Some queue the message and might not upload the messages until much later.
3. Some integrations might not even have loaded when you call track.

The idea behind the timeout is that it's a reasonable estimate of "hey, if everything went well, the event has been sent to integrations". Don't use it as a guarantee.

**Comment by f2prateek** [comment]
(I've closed the issue as I don't think there is a great solution here - but feel free to reopen or leave ideas).
