### ISSUE TITLE
How to get the latest version from integrations (Sentry for example)

### ISSUE THREAD

**Issue by danieleleoni** [segmentio/analytics.js#543]
Hi guys,
I'm trying to integrate Sentry using analytics.js from npm
`"analytics.js": "^2.9.1",`
but I'm getting 1.1.6 version, even if I see there is a 3.x.x available?

Just using window.analytics.initialize({'Sentry': {config: "MY_CONFIG_ID" }}) from Chrome Console.

Could this piece of code be interesting for my problem?
https://github.com/segmentio/analytics.js/blob/12a1fd045ffd7652dad8aaf15391905666bbb5b0/component.json#L87

Thanks!

**Comment by danieleleoni** [comment]
For what I understand, it seems that we could update component.json and then remake `make build`, but it is not working and analytics.js is a lot smaller than the one we found into this repository

**Comment by pooyaj** [comment]
Closing this, as using this repo for running `analytics.js` is not recommended. Should rely on the bundle from our CDN.
