### ISSUE TITLE
Uncaught Error: cannot find module "is-empty"

### ISSUE THREAD

**Issue by ccoffey** [segmentio/analytics.js#544]
I've successfully built analytics.js but when I tried to include it on a page, I get the following error.

<img width="498" alt="screen shot 2017-04-14 at 11 09 38 am" src="https://cloud.githubusercontent.com/assets/456400/25040692/e8dc8404-2102-11e7-9b0d-c87f325c23ff.png">

**Steps to build**

1. nvm install 0.12.0
2. remove clicktale & fullstory from `lib/integrations.js` because they seem to require private repo access: issue https://github.com/segmentio/analytics.js/issues/517
3. build make

**Steps to test**

1. I created a test page index.html which uses the snippet provided by the [Quickstart: Analytics.js](https://segment.com/docs/sources/website/analytics.js/quickstart/) guide. The only change I made was e.src now points to my locally built `analytics.js`

```javascript
e.src="./analytics.js"
```

Full script for completeness

```javascript
<script type="text/javascript">
  !function(){var analytics=window.analytics=window.analytics||[];if(!analytics.initialize)if(analytics.invoked)window.console&&console.error&&console.error("Segment snippet included twice.");else{analytics.invoked=!0;analytics.methods=["trackSubmit","trackClick","trackLink","trackForm","pageview","identify","reset","group","track","ready","alias","debug","page","once","off","on"];analytics.factory=function(t){return function(){var e=Array.prototype.slice.call(arguments);e.unshift(t);analytics.push(e);return analytics}};for(var t=0;t<analytics.methods.length;t++){var e=analytics.methods[t];analytics[e]=analytics.factory(e)}analytics.load=function(t){var e=document.createElement("script");e.type="text/javascript";e.async=!0;e.src="./analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(e,n)};analytics.SNIPPET_VERSION="4.0.0";
  analytics.load("YOUR_WRITE_KEY");
  analytics.page();
  }}();
</script>


```

**Comment by brightsparc** [comment]
@ccoffey Did you resolve?  i'm getting the same issues in attempting to build.

**Comment by balazs-endresz** [comment]
@brightsparc The master branch seems to be completely broken but this PR worked fine for me: https://github.com/segmentio/analytics.js/pull/514

**Comment by brightsparc** [comment]
@balazs-endresz thanks, i've got this fork and building, but when I include the script in my page it doesn't seem to send events to api, did you get this working as well?

**Comment by balazs-endresz** [comment]
I don't know about that, we're _not_ using it with segment.com, only with some other integrations.
