### ISSUE TITLE
TypeError: undefined is not an object

### ISSUE THREAD

**Issue by jasondonnette** [segmentio/analytics.js#546]
In Safari Version 10.1 (11603.1.30.0.34), OSX, I am getting:

> TypeError: undefined is not an object (evaluating 't.parentNode')

It comes from line 7385 of analytics.min.js
`r(function() {
  var t = document.getElementsByTagName("script")[0];
  t.parentNode.insertBefore(o, t)
});`

**Comment by f2prateek** [comment]
Hey @jasondonnette, sorry for the delay.  If this is still an issue, could you please reach out via https://segment.com/contact and our support team can investigate this further.
