### ISSUE TITLE
page() sync problems

### ISSUE THREAD

**Issue by hbernardo** [segmentio/analytics.js#549]
We are having problems with analytics.js snippet (got from https://segment.com/docs/sources/website/analytics.js/quickstart/), page() is not working sometimes randomly.
There is any asynchronous function that I should wait before using page?

Thanks.

`<script type="text/javascript">
  !function(){var analytics=window.analytics=window.analytics||[];if(!analytics.initialize)if(analytics.invoked)window.console&&console.error&&console.error("Segment snippet included twice.");else{analytics.invoked=!0;analytics.methods=["trackSubmit","trackClick","trackLink","trackForm","pageview","identify","reset","group","track","ready","alias","debug","page","once","off","on"];analytics.factory=function(t){return function(){var e=Array.prototype.slice.call(arguments);e.unshift(t);analytics.push(e);return analytics}};for(var t=0;t<analytics.methods.length;t++){var e=analytics.methods[t];analytics[e]=analytics.factory(e)}analytics.load=function(t){var e=document.createElement("script");e.type="text/javascript";e.async=!0;e.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(e,n)};analytics.SNIPPET_VERSION="4.0.0";
  analytics.load("YOUR_WRITE_KEY");
  analytics.page();
  }}();
</script>`

**Comment by f2prateek** [comment]
Hey @hbernardo , sorry for the delay.  If this is still an issue, could you please reach out via https://segment.com/contact and our support team can investigate this further.
