### ISSUE TITLE
trackForm is not working

### ISSUE THREAD

**Issue by theromie** [segmentio/analytics.js#552]
`var form = document.getElementById('contact_form');
analytics.trackForm(form,"Contact Page",function(form){
	var name = document.querySelector('input[name="name"]').value;
	var email = document.querySelector('input[name="email"]').value;
	var message = document.querySelector('input[name="message"]').value;
	return{
	     name: name,
	     email: email,
	     message: message,
	}
});`
I am trying to get data when user click on form button but its not working
I have created one common js file for all page which will get page name as value and in switch case i am passing value of page name and in case i am performing track method but it its working for only one page not for all page.

**Comment by f2prateek** [comment]
sorry for the delay. if you're still facing this issue, could you write into support (https://segment.com/contact) with the details and somebody from our team can help you out.
