### ISSUE TITLE
Console error after loading the analytics

### ISSUE THREAD

**Issue by vikasrohit** [segmentio/analytics.js#553]
Following error started to appear since last few weeks.

`VM2057:1 Uncaught TypeError: Cannot read property 'on' of undefined
    at <anonymous>:1:40
    at r.run (analytics.min.js:9)
    at i (analytics.min.js:9)`

More details when I clicked on the particular line of error

`window.drift.on("startConversation",function(a){ga("send","event","Drift Widget","Chat Started")})}`

I think it is not finding the drift object in window object. We are not using any drift integration here or doing anything related to drift. Can you please let us know what is the issue here?

**Comment by vikasrohit** [comment]
@ianstormtaylor @calvinfo do you guys happen to know anything related to this?

**Comment by calvinfo** [comment]
Unfortunately I don't, it's been some time since I've worked in this codebase. :(. 

Do you mind filling out a the form here? Someone should get back to you shortly! https://segment.com/help/contact

**Comment by vikasrohit** [comment]
Thanks @calvinfo for the quick response. I have already filled that form even before posting here. :) No replies yet.

**Comment by casesandberg** [comment]
Looking into it and analytics.js doesn't have anything to do with drift either: https://github.com/segmentio/analytics.js/search?utf8=%E2%9C%93&q=startConversation&type=

Is it possible that your code is calling drift somewhere?

**Comment by vikasrohit** [comment]
Thanks @casesandberg for looking into it. I have checked the application and its few dependencies, but didn't find any reference to drift yet.
Meanwhile I got response from segment customer support. I am following up there. I would update the results here once sorted out, to close the thread.

**Comment by f2prateek** [comment]
hey @vikasrohit, let me know if support wasn't able to help out here and I can escalate it internally.

**Comment by vikasrohit** [comment]
Thanks @f2prateek for follow up. I got it fixed. It was because of Google Tag Manager being added as destination.
