### ISSUE TITLE
analytics.js data reliability (security) issue

### ISSUE THREAD

**Issue by djokage** [segmentio/analytics.js#554]
The data collected and sent by analytics.js are not reliable as they can be generated and simulated by competitors to fake users behiviours to what is suitable for them. there is no obfuscation or any thing made to make it hard at least for script kiddies, or least a note so that analytics users would know this.
We can simulate thousands of users doing a given action by generating userIDs, messageIDs and events,
Also for logged in users, many websites use incremental userID, or can find the userID through their website blogs, forum or posts they submit ..., so knowing this ID we can simulate users behaviour which will lead the website marketing team to target this user depending on this behaviour which is completely false and can lose their clients in larger scale.

**Comment by f2prateek** [comment]
Hey @djokage, sorry for the delay here.


Unfortunately,  I don't think there's any changes we can make to analytics.js itself to prevent this from happening - but we will definitely be making improvement at our API layer to prevent such misuse. We think these two tools (in conjunction) will go a long way:

1. Origin header whitelisting -  so specific writekeys are only usable if a certain Origin header is present. This stops someone copy and pasting the write key but not someone maliciously tainting your data by calling `analytics.track` from your website multiple times.
2. Per IP Ratelimits - To prevent someone from purposefully sending lots of bad events, we'll have per IP address rate limits.

**Comment by f2prateek** [comment]
I'm closing this issue as there isn't any action to take on analytics.js itself here (unless you have any other suggestions as well!) — the improvements will be made at our API layer.
