### ISSUE TITLE
Server side rendering

### ISSUE THREAD

**Issue by yhjor** [segmentio/analytics.js#556]
I am using Next.js to develop a SSR react app. When I try to use `analytics-node` package it ships with native node code which results in error during Webpack build in client. When I try to use the `analytics.js` library it shows `window` is not defined error during import.

After reviewing the documentation in segment.io, it appears that there isn't a valid way to use with SSR app like Next.js. Any suggestion?

**Comment by danieleleoni** [comment]
We use segment into a SSR application, but only when there is an interaction with the client.
We had probably the same problems you had. 

So we load 
segmentio/analytics.js

then import it (even into a shared/universal component)
`import analytics from 'analytics.js'`

and use it
`analytics.track('EVENT XXX', data)`

So be sure just to call it only when client is up and running

**Comment by yhjor** [comment]
https://github.com/danieleleoni Thanks for replying. How about the API key? How can we initialize it?

**Comment by danieleleoni** [comment]
(open-source) Segment does not need key anymore, it is not like segment.io web interface
What you pay for segment is the web interface, not the service itself.

If you are referring for example to Google Analytics, you can still enable it with a code like
```
analytics.initialize({
  'Google Analytics': {
      trackingId: 123,
  },
})
```

The key `trackingId` is specific for Google Analytics. Sentry for example use `config`, Intercom `appId` and so on ...

**Comment by yhjor** [comment]
https://github.com/segmentio/analytics.js/issues/556#issuecomment-334983891
I don't think it is clearly documented here https://segment.com/docs
or May I have the URL with similar example?
