### ISSUE TITLE
using analythics.js in a React app without using ReactGA

### ISSUE THREAD

**Issue by muscaiu** [segmentio/analytics.js#557]
How can i use [analytics.js][1] in a React App without using [ReactGA][2]?

Is there any way to use it without importing it in the usual html way? ....

    < script type= "text/javascript" >
        !function () {
            var analytics = window.analytics = window.analytics || []; if (!analytics.initialize) if (analytics.invoked) window.console && console.error && console.error("Segment snippet included twice."); else {
            analytics.invoked = !0; analytics.methods = ["trackSubmit", "trackClick", "trackLink", "trackForm", "pageview", "identify", "reset", "group", "track", "ready", "alias", "debug", "page", "once", "off", "on"]; analytics.factory = function (t) { return function () { var e = Array.prototype.slice.call(arguments); e.unshift(t); analytics.push(e); return analytics } }; for (var t = 0; t < analytics.methods.length; t++) { var e = analytics.methods[t]; analytics[e] = analytics.factory(e) } analytics.load = function (t) { var e = document.createElement("script"); e.type = "text/javascript"; e.async = !0; e.src = ("https:" === document.location.protocol ? "https://" : "http://") + "cdn.segment.com/analytics.js/v1/" + t + "/analytics.min.js"; var n = document.getElementsByTagName("script")[0]; n.parentNode.insertBefore(e, n) }; analytics.SNIPPET_VERSION = "4.0.0";
                analytics.load("YOUR_WRITE_KEY");
                analytics.page();
            }
        }();
    </script >

I tried something like this and it doesn't work

    import ga from 'analytics'

    ga('send', 'pageview', '/mypage');

  [1]: https://github.com/segmentio/analytics.js?files=1
  [2]: https://github.com/react-ga/react-ga

**Comment by f2prateek** [comment]
Sorry for the delay!

```
import ga from 'analytics'

ga('send', 'pageview', '/mypage');
```

I wouldn't really expect that ^ to work - it's importing analytics.js but calling Google Analytics methods on it.

At segment, our  web app just calls (after adding the script tag in the body as you did):

```
window.analytics.page('Integrations Catalog');
```

If you're having issues with this - please write in to our support team https://segment.com/contact, and they can help out!
