### ISSUE TITLE
Duplicate page() call on initial load

### ISSUE THREAD

**Issue by phlare** [segmentio/analytics.js#558]
I'm building segment into a react app and am having some trouble with duplicate page() calls on the initial load when a user lands on my site.

even if i completely remove the page()  call from the suggested snippet,  I still receive a page() item in the debugger on the initial landing.

It seems that simply loading the snippet for the first time and calling the load() function to set it up creates some kind of inherent page() call, which is then duplicated by the following page() in the suggested snippet.

is there a way to eliminate this duplication?  once the page is loaded, clicking around to other routes fires the page() calls as I would expect, but I'm worried that that duplicate initial call will skew my analytics.

**Comment by f2prateek** [comment]
Be sure to pass in `initialPageview` as false https://github.com/segmentio/analytics.js-core/blob/3b48c44a3d6537a9e695810292101be8c2bb2dee/lib/analytics.js#L56.
