### ISSUE TITLE
Prevent duplicate events from being transmitted to providers 

### ISSUE THREAD

**Issue by niftylettuce** [segmentio/analytics.js#562]
Is it possible to use a unique identifier in the `properties` object with Segment so that if I send 100 of the same event, Segment will only record/transmit it to providers once?

For example:

```js
analytics.track('Some Event', { id: '123456', favorite_color: 'blue' });
analytics.track('Some Event', { id: '123456', favorite_color: 'blue' });
analytics.track('Some Event', { id: '123456', favorite_color: 'blue' });
analytics.track('Some Event', { id: '123456', favorite_color: 'blue' });
analytics.track('Some Event', { id: '123456', favorite_color: 'blue' });
analytics.track('Some Event', { id: '444555', favorite_color: 'red' });
```

In this example only two events would get sent to providers such as Facebook Pixel or AdRoll (one event for id `123456` and another for `444555`.

This would be a complete solution for timeout/delay issues and provide accurate and reliable event tracking.

**Comment by f2prateek** [comment]
No, this isn't really possible. There is a messageId (which the library will handle for you) but it mostly applies to server side tools as most client side tools don't use it https://segment.com/docs/spec/common/#structure.
