### ISSUE TITLE
Unable to see tracking events in browser

### ISSUE THREAD

**Issue by ferozed** [segmentio/analytics.js#563]
I am self hosting analytics.js. I have a webserver on my machine on which I have analytics.js and a web page that uses analytics. However, no matter what I try, I do not see tracking events going out on page load.

Is there some magic api that needs to be called to get analytics.js to send events? I do not even see a call to segment's endpoint.

Any help appreciated.

**Comment by f2prateek** [comment]
No integrations are enabled by default, you need to initialize the tools you are using. Since you are using the self hosted version, there are no calls sent to Segment either.

I'd recommend using the hosted version first so you understand how it works https://segment.com/docs/sources/website/analytics.js/quickstart/.

**Comment by ferozed** [comment]
Thanks for your response. However, there is no documentation I am aware of that shows how to initialize the integrations. Also, in the open source version, can the send to segment be enabled at all? or is it not supported?

**Comment by f2prateek** [comment]
Yes the documentation is pretty sparse, I'd check out the tests in analytics.js-core https://github.com/segmentio/analytics.js-core/blob/master/test/analytics.test.js for a starting point. You can still send data to any of of the tools listed here (including segment). https://github.com/segment-integrations?q=analytics.js-integration

**Comment by ferozed** [comment]
I built analytics.js from scratch using this repo. When I try to use it, I get this exception.

`analytics.js:27 Uncaught Error: cannot find module "is-empty"
    at require (analytics.js:27)
    at analytics.js:49
    at Object.45.type (analytics.js:1470)
    at call (analytics.js:47)
    at require (analytics.js:26)
    at analytics.js:49
    at Object.39.is (analytics.js:1397)
    at call (analytics.js:47)
    at require (analytics.js:26)
    at analytics.js:49`

Any ideas how to fix it?
