### ISSUE TITLE
on Safari, unload and beforeunload events can't make segment request

### ISSUE THREAD

**Issue by EDalSanto** [segmentio/analytics.js#565]
Having same issue as this [person here](https://stackoverflow.com/questions/34232134/safari-does-not-run-callback-function-on-refresh-onbeforeunload-on-server-side) . In short: Segment requests are async and Safari does not wait for async requests when unloading the page, so we lose events about our users. Only workaround is the Beacon API which is not supported by all browsers yet. 

Has anyone else encountered this issue?

**Comment by f2prateek** [comment]
The requests must be async otherwise your users will have a poor customer experience. We've added persistent queues for this reason (https://github.com/segment-integrations/analytics.js-integration-segmentio/commit/aae60a40f8fae099cc58aba12141738abddcc909), this is currently being tested behind a flag.

**Comment by EDalSanto** [comment]
So it's been tested with scenarios like I mentioned? 

What's the easiest way to integrate it into our normal flow?

**Comment by benedictfischer09** [comment]
Is there a problem with using feature detection to see if `Navigator.sendBeacon` is available and defaulting to that and then falling back to `XMLHttpRequest` when its not there?

**Comment by f2prateek** [comment]
Sorry for the delay - we had considered doing that originally (https://github.com/segment-integrations/analytics.js-integration-segmentio/commit/2801ef5d45678c86579dfb9448ffa46449b4db54), but ultimately decided against it for various reasons.

**Comment by f2prateek** [comment]
If you'd like to beta test the retry queue functionality (the one in https://github.com/segment-integrations/analytics.js-integration-segmentio/commit/aae60a40f8fae099cc58aba12141738abddcc909), please reach out to our support team via http://segment.com/contact and they can get you setup.

**Comment by khesualdo-clio** [comment]
@f2prateek Hi, I am looking to try the retry queue functionality, do I still need to contact the support team for this to be enabled? If so, I go to Contact Us -> Tech Support-> Technical Support, I see a contact form, but no where to input my contact info, how will the support contact me about my question, do I need to be logged in?

**Comment by eunjae-lee** [comment]
> Sorry for the delay - we had considered doing that originally ([segment-integrations/analytics.js-integration-segmentio@2801ef5](https://github.com/segment-integrations/analytics.js-integration-segmentio/commit/2801ef5d45678c86579dfb9448ffa46449b4db54)), but ultimately decided against it for various reasons.

Hello @f2prateek I know it's been a long time since you left the comment, but if you still remember, can you help me understand what the reasons were for you to decide against sendBeacon?

**Comment by fred-boink** [comment]
@eunjae-lee This feature would be great to send a final message to segment that the app is closing.
