### ISSUE TITLE
What is the best way to integrate this in a vue project?

### ISSUE THREAD

**Issue by xerosanyam** [segmentio/analytics.js#567]
I found a vue plugin https://github.com/Glovo/vue-multianalytics, but it supports some features of segment afaik.

Can anyone with knowledge of both Segment and Vue guide me on best practices of implementing Segment in a vue project. Also benefits/drawbacks of using this plugin over native

**Comment by f2prateek** [comment]
hey @xerosanyam - sorry for the delay. I haven't worked with vue before, but hopefully you found your answer. If not - I might suggest reaching out via http://segment.com/contact and our support team can help you get setup with analytics.js
