### ISSUE TITLE
Respect Do Not Track Rules

### ISSUE THREAD

**Issue by ghost** [segmentio/analytics.js#569]
Noticed #130 was closed without much thoughtful discussion. In light of GDPR landing in a coupe weeks I'd like to revive the DNT discussion here with a new spin:

Update library to automatically set `ip` in the `context` prop to `0.0.0.0` when…

```
window.navigator.doNotTrack || window.doNotTrack || window.navigator.msDoNotTrack
```

Obviously there's no reason not to load and track useful analytics data so long as we're stripping all PII and other data which could be used to fingerprint a user when they've elected DNT, ya?

**Comment by f2prateek** [comment]
We didn't re-open #130, but it motivated the the work done for Do Not Track here https://github.com/segmentio/analytics.js-core/pull/36!

As you can tell though - the DNT setting can be interpreted in multiple ways  - you suggested don't collect IP address, https://github.com/segmentio/analytics.js-core/pull/36 does it by not collecting any events. Ultimately it was hard to come up with a one-size fits all solution in analytics.js itself, so we decided not go forward with https://github.com/segmentio/analytics.js-core/pull/36. For now I'd recommend using a helper function like this:

```
function track(event, props) {
  if (window.navigator.doNotTrack || window.doNotTrack || window.navigator.msDoNotTrack) {
    analytics.track(event, props, { context: { ip: '0.0.0.0' }});
  } else {
     analytics.track(event, props);
  }
}
```

We do have some exciting improvements coming down to help with this that build on top of https://github.com/segmentio/analytics.js-core/pull/36. It will be open sourced within a couple of weeks and work on top of analytics.js to not only make it easy to respect Do Not Track rules, and goes above and beyond what's required by GDPR. Keep an eye out on the blog https://segment.com/blog/

**Comment by jhabdas** [comment]
Thanks for the info @f2prateek. That's helpful. I'm certainly not looking for a one-size fits all solution. But to respect the spirit of DNT and GDPR I feel the helper function provided should be cooked into core so users don't flub it. What are your thoughts?

**Comment by f2prateek** [comment]
absolutely - i'll post back here when that library is open sourced.

**Comment by jhabdas** [comment]
Saw it. Didn't resolve the issue. I found a better analytics library. Thanks!

**Comment by jhabdas** [comment]
It's not exactly what I was looking for but I found an alternative that works for my needs. Thanks.
