### ISSUE TITLE
Upgrade rollbar 

### ISSUE THREAD

**Issue by quinnbaetz** [segmentio/analytics.js#570]
rollbar.js version 2.3.1 is now available. (This project is currently using version 2.2.7). View release notes

**Comment by f2prateek** [comment]
Hey @quinnbaetz, could you open this issue in this repo where that is controlled - https://github.com/segment-integrations/analytics.js-integration-rollbar

**Comment by f2prateek** [comment]
I might also shoot a request via http://segment.com/contact to make sure this gets seen by the right team.
