### ISSUE TITLE
Porting ga('set', ... ) calls

### ISSUE THREAD

**Issue by ferozed** [segmentio/analytics.js#571]
I am porting some ga code to use segment. There are the ga('set', .... ) calls for which I dont see a corresponding version in analytics. It is not possible to pass in the custom dimensions as properties because they were being set in a different part of the page, and the track/page calls happen elsewhere.

What do you suggest we do to solve this?

**Comment by f2prateek** [comment]
hey @ferozed - your issues sounds specific to the Google Analytics integration. Could you open a ticket the [Google Analytics integration repository](https://github.com/segment-integrations/analytics.js-integration-google-analytics) instead?

I might also shoot a request via http://segment.com/contact to make sure this gets seen by the right team.

**Comment by ferozed** [comment]
Well, it is google related but it is applicable outside of google as well.

What I am proposing is, we add a `Analytics.prototype.set(props)` method. The props would be buffered internally. And when users call `track` or `page` or `identify`, the properties passed in to the api calls would be merged with those passed in with the `set` call.

**Comment by f2prateek** [comment]
I don't think we should add this to analytics.js unless we have a examples of multiple tools needing this functionality.

For now I think this logic should either live in the GA integration, or you can call into GA directly.
