### ISSUE TITLE
Makefile fails with "not found: make-package.json"

### ISSUE THREAD

**Issue by NitroBAY** [segmentio/analytics.js#573]
Hello,
Following [auto-analytics](https://github.com/okgrow/auto-analytics)' advice I'm building your package (through Makefile's build option) but if fails (I've installed package through Windows GNU first but it was saying "node_modules" is not an internal command so I `npm install -g make`) reading "not found: make-package.json" failing at the node_modules step.
Thanks you very much for any help I could get.

**Comment by NitroBAY** [comment]
BTW I'm about to deploy my app for some reasons I had to switch the package used for tracking any workaround to compile properly only the few integration I want ( Ganalytics, pixel etc.) and not all one will be very appreciated. Thanks.

**Comment by f2prateek** [comment]
I would strongly recommend using the method recommended here https://segment.com/docs/sources/website/analytics.js/quickstart/.

**Comment by NitroBAY** [comment]
Well okay I didn't know segment but seems like a great tool. Thanks.

**Comment by waltster** [comment]
Can this issue be closed?
