### ISSUE TITLE
analytics.js suitable with react-native ?

### ISSUE THREAD

**Issue by kevindavee** [segmentio/analytics.js#574]
Hello,

I want to ask if analytics.js is suitable for react-native ? is it possible for me to implement this SDK to react-native ?

If not, do you have any way out ? We would like to use segment.com products with our react-native app.

Thank you

**Comment by PerStirpes** [comment]
I think your answer can be found here: https://community.segment.com/search#react%20native

**Comment by f2prateek** [comment]
Sorry for the delay, we have a react native library in beta that you can use now! https://github.com/segmentio/analytics-react-native
