### ISSUE TITLE
Intercom avatar does not work

### ISSUE THREAD

**Issue by wlodi83** [segmentio/analytics.js#575]
I use Segment with Intercom as destination. I call identify method with following traits including avatar:

`
{
  "anonymousId": "9ced94d7-ff14-43cf-8de7-7ca369f08123",
  "context": {
    "library": {
      "name": "analytics.js",
      "version": "3.6.0"
    },
    "page": {
      "path": "/settings",
      "referrer": "http://localhost:3000/",
      "search": "",
      "title": "",
      "url": "http://localhost:3000/settings"
    },
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36",
    "ip": "88.130.49.240"
  },
  "integrations": {
    "Intercom": {
      "user_hash": ""
    }
  },
  "messageId": "ajs-84fa35d930459195e4716094540b1466",
  "receivedAt": "2018-06-26T13:24:49.456Z",
  "sentAt": "2018-06-26T13:24:49.367Z",
  "timestamp": "2018-06-26T13:24:49.454Z",
  "traits": {
    "avatar": "https://avatars.slack-edge.com/2017-10-25/261873774229_6552d4440aaa8197232a_32.jpg",
    "company": {
      "createdAt": "2018-06-26T13:16:24.765Z",
      "dataRetentionPolicy": 90,
      "employee_count": 1,
      "id": "TAdYDMmT9JW4c4hRQ",
      "name": "test",
      "phone": "12345678",
      "plan": "Free Plan"
    },
    "createdAt": "2018-06-26T13:16:24.759Z",
    "email": "lukasz@test.io",
    "id": "5rLrjDQ4iZW3MB5XW",
    "name": "Lukasz",
    "phone": "12345678",
    "role": "owner",
    "username": "lukasz@test.io"
  },
  "type": "identify",
  "userId": "5rLrjDQ4iZW3MB5XW",
  "originalTimestamp": "2018-06-26T13:24:49.365Z"
}
`

Response from Intercom indicates that avatar is not populated:

`
"body": {
    "anonymous": false,
    "app_id": "sfx4acay",
    "avatar": {
      "image_url": null,
      "type": "avatar"
    }
`

How to build traits properly in order to have avatars displayed in Intercom?

**Comment by f2prateek** [comment]
hey @wlodi83  - I'd recommend opening a ticket with our support team https://segment.com/contact
