### ISSUE TITLE
Google Canary Console Warnings

### ISSUE THREAD

**Issue by jcristol** [segmentio/analytics.js#579]
- When installing the segment snippet in index.html of my app.
- Warnings are generated every page load.

Warnings are as follows.
- HTTP-Based Public Key Pinning is deprecated. Chrome 69 and later will ignore HPKP response headers. (Host: s.yimg.com)
- HTTP-Based Public Key Pinning is deprecated. Chrome 69 and later will ignore HPKP response headers. (Host: sp.analytics.yahoo.com)
- HTTP-Based Public Key Pinning is deprecated. Chrome 69 and later will ignore HPKP response headers. (Host: ads.yahoo.com)

Seems like segment is using HTTP public key pinning.

**Comment by f2prateek** [comment]
I don't think this is from Segment. This looks to be using one of the tools you are using, ones that make requests to "s.yimg.com", "sp.analytics.yahoo.com" and "ads.yahoo.com"

**Comment by f2prateek** [comment]
I'm going to close this out as I don't think this is an issue with analytics.js itself, but rather the tools you are using. Feel free to write into https://segment.com/contact with any follow ups though, or reopen this issue if you think it was in error.
