### ISSUE TITLE
window.analytics reference changes causing subtle bugs

### ISSUE THREAD

**Issue by sanbornhilland** [segmentio/analytics.js#580]
As far as I can tell, when the library loads, it stubs out the API at `window.analytics` and then enqueues operations until the library has fully loaded. But once its loaded it *changes* the `window.analytics` reference. Anything that has a reference to the original object is now left enqueuing operations and its not at all obvious why its failing to send events.

If you wanted to e.g. inject `analytics` into some service instead of using the global object directly you end up with confusing behaviour. Here is a contrived example:
```javascript
const wrapService = (analytics) => {
	setTimeout(() => {
 		window.analytics === analytics // false
        // Any calls to analytics will not be sent if you call analytics.X
        // you HAVE to call window.analytics because the ref has changed
	}, 1000)
}

// If this is called too soon then the analytics calls 
// inside `wrapService` will fail
wrapService(window.analytics)
```

I understand the library is loading asynchronously but changing out the lib ref like that seems highly unexpected to me. I don't see why I shouldn't be able to pass `window.analytics` as an argument and have it work.

**Comment by f2prateek** [comment]
Duplicate of https://github.com/segmentio/analytics.js-core/issues/59. Do you mind moving your comment over to that issue and closing this out?

**Comment by sanbornhilland** [comment]
@f2prateek Ahh yes sorry. I wasn't aware of that repo.
