### ISSUE TITLE
Open source segment analytics.js glue code

### ISSUE THREAD

**Issue by e1himself** [segmentio/analytics.js#583]
Hey, Segment Team :)

Is there a chance you will open-sources the glue code used to serve analytics.js via segment account? (I know this repo is for a generic segment-account-unaware lib), but I don't know where else to ask this question.

I'm asking this because I'm currently struggling on setting analytics.js cookie domain. One of the ways to do so would be to have access to the segment.com served glue code that is served for the account. When I'm saying *access* I mean *see the code and possibly suggest a change with a Pull Request*. :)

I've also asked a related question via community: https://community.segment.com/t/y72wxg

Thanks!

**Comment by f2prateek** [comment]
We're thinking about it, but don't have any concrete plans currently (or an ETA).

However, ~95% of client side code served is made up of open source components, so it shouldn't block from debugging issues.

Re: the cookie issue (depends on the cookies you are looking) but is likely this one - https://github.com/segmentio/analytics.js-core/blob/master/lib/cookie.js#L40-L48

**Comment by f2prateek** [comment]
I think there's two issues here. Firstly, analytics.js-core itself doesn't have a way to customize the domain (open source part). i.e. just `analytics.options` doesn't do anything even if you;'re using analytics.js-core directly. We would likely need to make some changes here first (and then figure out how to pass those via the snippet).

However, we haven't really heard demand for this kind of feature, so it's unlikely that this will get prioritized soon. If you'd like - you can open an issue on https://github.com/segmentio/analytics.js-core to file a request and track the status (and this will also allow others to show interest which will help us bump it in priority).

**Comment by e1himself** [comment]
@f2prateek 

> I think there's two issues here. Firstly, analytics.js-core itself doesn't have a way to customize the domain (open source part). 

This is false. 

It does provide a way to do so. You can pass it with `options` argument to `.initialize()`:

```js
analytics.initialize(settings, { cookie: { domain: 'app.company.com' });
```

This does work because cookie module accepts `options`:

- https://github.com/segmentio/analytics.js-core/blob/master/lib/cookie.js#L43-L48
- https://github.com/segmentio/analytics.js-core/blob/master/lib/analytics.js#L640
- https://github.com/segmentio/analytics.js-core/blob/master/lib/analytics.js#L112

But segment.com-served glue code that does not expose an entry point to provide extra options. That's the suggestion of my previous comment.

**Comment by e1himself** [comment]
>  If you'd like - you can open an issue on https://github.com/segmentio/analytics.js-core to file a request 

I'd love to do so, but the questioned code is *your closed source code* that glues open source parts. Thus I've opened this issue: *Open source segment analytics.js glue code* :)

**Comment by f2prateek** [comment]
Got it - you're right. I've opened an issue internally (LIB-619). I don't have an ETA, but I'd recommend writing in via https://segment.com/contact - this way we can email you when there are updates on this ticket.

**Comment by e1himself** [comment]
> but I'd recommend writing in via https://segment.com/contact

Thanks. I already did. 

Just for reference, it's request #158713

**Comment by f2prateek** [comment]
Thanks! Linked it to our internal JIRA!

**Comment by e1himself** [comment]
@f2prateek any updates here?

**Comment by digitalbase** [comment]
hi @f2prateek and segment team.

I want to raise a more general concern about the description of this library and the spirit of open source.

From the readme:

> Analytics.js is open source and is one of the libraries that powers Segment, the managed, hassle-free way to collect customer data in the browser and beyond.

While the reality is different: Because there is extra glue code on top of this library some options in this library are not available to segment.com customers.

My personal convincement is that one of the below suggestions would be fairer:

- add a clear disclaimer that explains to developers/companies evaluating the analytics SDK that some of these options might not be available as a commercial segment customer
- ensure that the glue code on top of this library does not restrict the power of this library

After reading the README of this library that has multiple calls to actions and promo to sign up for your product I can't help but have a bad taste in my mouth.
