### ISSUE TITLE
Getting errors with Require.js on Analytics.load() function

### ISSUE THREAD

**Issue by samybel** [segmentio/analytics.js#584]
I'm trying to implement Segment in my SPA written in Knockout, but I'm having errors when the analytics.load("MY API KEY") is called. I have inserted the snippet in my header and I'm having weird response in my app, if I refresh sometimes it works but most of the time it fails. 
I've seen this [issue](https://github.com/segmentio/analytics.js/issues/515) and I have simillar behavior, but at the end it seem the new version should have solved it, but for me it didn't.

**Comment by f2prateek** [comment]
hi - could you write in via https://segment.com/contact and our team can help debug the issue.
