### ISSUE TITLE
Uncaught TypeError: Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by rabashani** [segmentio/analytics.js#585]
Getting this from the analytics.js - you can see it here on app.loola.tv
Even on our anonymous homepage 

analytics.min.js:5 Uncaught TypeError: Cannot read property 'toLowerCase' of undefined
    at analytics.min.js:5
    at c (analytics.min.js:1)
    at u (analytics.min.js:1)
    at o (analytics.min.js:5)
    at t.p.page (analytics.min.js:5)
    at analytics.min.js:9
    at c (analytics.min.js:1)
    at u (analytics.min.js:1)
    at t.n.flush (analytics.min.js:9)
    at t.<anonymous> (analytics.min.js:9)

**Comment by f2prateek** [comment]
hey @rabashani if this is for the Semgent hosted version - please donate our support team (https://segment.com/contact) and they can help you debug this.

**Comment by jamesjjk** [comment]
@f2prateek Is this for real?

**Comment by f2prateek** [comment]
my mistake - I had a typo in the original comment. I meant please *contact* our support team (https://segment.com/contact) and they can help you debug this.
