### ISSUE TITLE
Sentry.io - This event was reported with an old version of the javascript SDK.

### ISSUE THREAD

**Issue by notmessenger** [segmentio/analytics.js#586]
The version of Sentry.io loaded by analytics.js is an older one, because the message of

> This event was reported with an old version of the javascript SDK.

is reported within Sentry.io screens which links to https://docs.sentry.io/clients/javascript/?_ga=2.186673704.18631651.1540901773-1641070921.1532617420 which says

>Deprecated Client
> This SDK has been superseded by a new unified one. The documentation here is preserved for customers using the old client. For new projects have a look at the new client documentation: [Unified Browser Javascript SDK](
https://docs.sentry.io/quickstart?platform=browser).

Sort of related to #543

**Comment by f2prateek** [comment]
I'd recommend opening the issue on https://github.com/segment-integrations/analytics.js-integration-sentry

**Comment by notmessenger** [comment]
Have opened https://github.com/segment-integrations/analytics.js-integration-sentry/issues/32 and am closing this issue.
