### ISSUE TITLE
Hosted analytics.js / CDN

### ISSUE THREAD

**Issue by philfreo** [segmentio/analytics.js#59]
I'd like to use analytics.js itself (rather than segment.io), but was wondering if you'd like to support a CDN'ed version of analytics.js without segment.io

I see from https://segment.io/close.io/setup/javascript/snippet that you have urls like https://d2dq2ahtl5zl1z.cloudfront.net/analytics.js/v1/x0cyzac/analytics.min.js (with a nice async loading snippet). Is there anywhere that doesn't require the segment.io api key?

**Comment by ombr** [comment]
I think pivotal did an article on it:

https://content.pivotal.io/blog/how-to-use-analytics-js-to-fix-your-analytics-code-and-achieve-metrics-nirvana
