### ISSUE TITLE
React.js Library

### ISSUE THREAD

**Issue by ian** [segmentio/analytics.js#598]
Kinda surprised that this doesn't exist already.  Many frontend solutions prefer not dropping a <script/> tag into head.  

Any plans for an async React library?

**Comment by f2prateek** [comment]
We ourselves use React for segment.com and use this approach and haven't run into issues, but I'm curious what other ways we could offer this?

Keep in mind that the Segment hosted version of  analytics.js needs to be loaded from a script tag/CDN because behind the scenes it's dynamically generating a different script for every project based on only the integrations that project uses.

**Comment by ajsharp** [comment]
@f2prateek Does analytics.js load synchronously? The more "standard" way to use it would be include it in package.json, and load it and init it in a javascript file.

I get what you're saying wrt to the script being generated dynamically. Maybe the solution is just better documentation on how to use it.

The current approach seems to be to assume it exists in the container environment, but this just feels kinda brittle.

**Comment by f2prateek** [comment]
Because of the dynamic generation piece, it has to load async as well. Here's an example we wrote recently https://github.com/segmentio/analytics-react

**Comment by ajsharp** [comment]
@f2prateek with the above is it possible to load two separate segment instances on a page for two separate projects? The use case here is for an embeddable website plug-in. Eg, if the host page Already has a segment instance loaded I still need to be able to log to segment from the embedded plug-in.

**Comment by kenhowardpdx** [comment]
> @f2prateek with the above is it possible to load two separate segment instances on a page for two separate projects? The use case here is for an embeddable website plug-in. Eg, if the host page Already has a segment instance loaded I still need to be able to log to segment from the embedded plug-in.

If you are relying on analytics.js you cannot have two instances on a single web page. You can look at using the HTTP API endpoint. The HTTP API endpoint requires you to provide your own anonymousId or userId and client-side timestamps.

**Comment by pooyaj** [comment]
Leaving this here for an example of using React/Sending data to multiple sources: https://github.com/segmentio/ajs-multiple-writekeys-demo
