### ISSUE TITLE
Using Analytics.js without segment.io subscription

### ISSUE THREAD

**Issue by VinayaSathyanarayana** [segmentio/analytics.js#599]
Is it Possible to use open source analytics.js to route the data directly to my destinations without using segment.io (or without subscribing to segment.io)

**Comment by liwangqiang** [comment]
Yes, you can.
This post may help you.  
http://www.ianww.com/blog/2017/08/06/analytics-js-standalone-library/

**Comment by pooyaj** [comment]
+1 to the above answer
