### ISSUE TITLE
Sending batch requests

### ISSUE THREAD

**Issue by markbrouch** [segmentio/analytics.js#608]
The HTTP API and node sdk allow for sending batches of events (https://segment.com/docs/sources/server/http/#batch), but not the client-side javascript SDK. Is this something that could be added? It would be nice to batch events with a configurable flush interval.

**Comment by Shub1427** [comment]
Any updates on this?

**Comment by pooyaj** [comment]
This is currently not on our roadmap. But I created a ticket internally to track it as a possible future improvement.

**Comment by Austio** [comment]
@pooyaj :wave: 

Wanted to check in on priority here.  Is there anything that we could do to help get this feature in the JS library?

**Comment by pooyaj** [comment]
@Austio 👋 I should correct my previous update, we are doing some fundamental improvements to JS library and request batching is in our plans. Not an exact ETA yet, but should be able to give a clear timeline in a couple of months.

**Comment by Austio** [comment]
@pooyaj heya.  Wanted to touch base and see how this was looking for batch support.

**Comment by Austio** [comment]
@pooyaj any updates on th ebatch support or plan for this issue?

**Comment by pooyaj** [comment]
@Austio Sorry for the delay. We are working on a new version of our JS library, and hoping to get the beta out somewhere in Q1. Will update the thread as soon as we make the new version available.

**Comment by tlalfano** [comment]
Hey @Austio and @markbrouch!

This is officially supported in Analytics.js 2.0 and documented here: https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/#batching
