### ISSUE TITLE
Analytics is not tracked when page is reloaded

### ISSUE THREAD

**Issue by DevCoding226** [segmentio/analytics.js#609]
Currently, Project is using segment for observing the track events.
I set all the configuration in the current project and it seemed to be Ok.
But, it is for some cases.
For most of cases, it doesn't track.

So, critical problem is that tracking is not triggered when I continuously reload page.
But when I create new tab and load website, analytics works fine.

Can anyone please help on this one?

**Comment by DevCoding226** [comment]
At first running, it is tracking successfully.
![image](https://user-images.githubusercontent.com/29897096/60760424-c7f9d900-a03d-11e9-9c0f-37255261a260.png)

After reloading the page, tracking is not triggered.
![image](https://user-images.githubusercontent.com/29897096/60760434-e7910180-a03d-11e9-8286-119a4d8d49a3.png)

**Comment by CaffGeek** [comment]
Did you find a solution to this?
