### ISSUE TITLE
Sending data to a custom endpoint

### ISSUE THREAD

**Issue by YLemelin09** [segmentio/analytics.js#610]
From what I understand this is how the data collection works:

Analytics.js --> segment --> endpoint from a list of options set by segment.

My company is developing its own data analyzing tool to use in our application. Is there anyway to have my data collection this way? 

Analytics.js --> my own endpoint

I was told by segment to use webhooks but it still relays the data to segment. In our mobile versions of the application it was apparently really straightforward to just relay from the analytics plugin to our endpoint.

Can I do this? If yes, how?

**Comment by kenhowardpdx** [comment]
Have you looked at [`analytics.on` method](https://segment.com/docs/sources/website/analytics.js/#emitter)? Or if you build your own analytics.js using https://github.com/segmentio/analytics.js-core you might be able to have your own integration subscribe to events: https://www.npmjs.com/package/@segment/integration-sdk

I've not attempted the custom build approach so I may be completely off base.

**Comment by 4074** [comment]
Mark. I want to know this too.

**Comment by pooyaj** [comment]
@YLemelin09 @4074 I second @kenhowardpdx response to the question. You can hook into `on` method and implement your own logic there. Documentation is here: https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/#emitter
