### ISSUE TITLE
Load integrations options are not properly merged with page/track methods integrations options

### ISSUE THREAD

**Issue by JosefCzanko** [segmentio/analytics.js#616]
In case that ‘integrations’ are passed as part of load options then it is impossible to override ‘integrations’ settings during page/track/identify calls.

I checked code in analytics.js which handles this and it seems to me that you are only calling ‘defaults’ function (https://github.com/ndhoule/defaults) which simply copy properties from one integrations to another.

I want to have following setup:
1. Enable only Google Analytics and Adobe analytics on page level
`analytics.load('writekey', { integrations: { All: false, 'Google Analytics': true, 'Adobe analytics': true } })`
2. I want to send specific track event just to Google Analytics
`analytics.track('EventName', {}, {
  integrations: {
    'All': false,
    'Google Analytics': true
  }
});`

So I want to be able to provide more restrictive integrations options on method level such as page/track/identify.

I hope that following code can be used to solve this issue
https://gitlab.com/snippets/1901703

**Comment by pooyaj** [comment]
@JosefCzanko we recently released a feature called middleware that lets you filter certain events from going into certain destinations. You have to write a middleware function that looks at the event payload and selectively disables integrations. Check out the docs here: 
https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/#middleware
