### ISSUE TITLE
Canonical URL is logged instead of actual URL

### ISSUE THREAD

**Issue by mkukawski** [segmentio/analytics.js#617]
Segment should not temper with the URL and replace it with Canonical tag value.
Note that Canonical is for SEO hinting, it has nothing to do with the actual page load.
Segment logs have nothing to do with SEO.
Also, it's broken as it's not recognizing relative Canonical URL's.
Please change this or at least give an option on Source level whether this should be enabled.

No, I don't want workaround in a form of passing {url: } in .page() - all event tracking is affected, I don't want to override everywhere and keep track of that.

**Comment by yepelinux** [comment]
Same problem here at www.cliengo.com?utm_plan=test

Any solution?

**Comment by pooyaj** [comment]
@mkukawski Yes, segment is Canonical URL. We recently released a feature called middleware that allow changing the payload. You can probably write a source middleware ( a JS function ) that changes the way URL is tracked. More info on Middleware: 
https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/#middleware
