### ISSUE TITLE
How to initialize Analytics.js with my key? Version 2.11.0

### ISSUE THREAD

**Issue by zohaib10** [segmentio/analytics.js#620]
I've have added the minified script to my code and I see `analytics` on the window object. My Question is how do I tell Analytics what my `Api key` or `Write key` is? I am unable to use the latest version which has the function `load` on it.   Thanks for the help in advance. 😄

**Comment by pooyaj** [comment]
We recommend using either the CDN version, or if you like to go to `npm` route, then use [this example]( (https://github.com/segmentio/ajs-multiple-writekeys-demo) ) to import and use analytics library
