### ISSUE TITLE
Add defer attribute in JavaScript snippet

### ISSUE THREAD

**Issue by addy5** [segmentio/analytics.js#622]
In the recommended implementation:
```
<script type="text/javascript">
  !function(){var analytics=window.analytics=window.analytics||[];if(!analytics.initialize)if(analytics.invoked)window.console&&console.error&&console.error("Astronomer snippet included twice.");else{analytics.invoked=!0;analytics.methods=["trackSubmit","trackClick","trackLink","trackForm","pageview","identify","reset","group","track","ready","alias","page","once","off","on"];analytics.factory=function(t){return function(){var e=Array.prototype.slice.call(arguments);e.unshift(t);analytics.push(e);return analytics}};for(var t=0;t<analytics.methods.length;t++){var e=analytics.methods[t];analytics[e]=analytics.factory(e)}analytics.load=function(t){var e=document.createElement("script");e.type="text/javascript";e.async=!0;e.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.astronomer.io/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(e,n)};analytics.SNIPPET_VERSION="3.1.0";
  analytics.load("YOUR_APP_ID");
  analytics.page()
  }}();
</script>
```

I see the `e.async=!0;` property set, but is there any reason not to add/replace with a `e.defer=!0;` property so the script does not prevent HTML parsing?

**Comment by pooyaj** [comment]
@addy5 the `async` was used so that the script is executed as soon as it is downloaded. But if you prefer the use of `defer` for performance gains, you can change the snippet to your need on your website. I don't think it has any side-effects since snippet still queues the calls to `track`, etc. and empties the queue when the script finishes loading.

**Comment by rtymchyk** [comment]
@pooyaj If there are no side-effects or disadvantages, I think there's no reason not to have `defer` as the default. In our case, `analytics.js.min` takes 200ms to evaluate, which is pretty massive given that our main bundle takes 500ms. The documentation implies that there is no load performance impact, but there is.
