### ISSUE TITLE
Date time conversion happening automatically

### ISSUE THREAD

**Issue by matteopey** [segmentio/analytics.js#623]
Hello, 
I'm seeing a problem when sending a Page event with the library.
Inside the properties object I pass a property with a value like this one: `2020-01-16 14:10:59` which should be kept as a string, but on the debugger I see a different value `2020-01-16T13:10:59.000Z` so it seems like there is a conversion happening in the background.

Is it possible to keep the string as the original?

Thank you.

**Comment by pooyaj** [comment]
@matteopey if still an issue, does this happen to specific properties or every custom property you set?

**Comment by pooyaj** [comment]
After looking into this, there is an intentional conversion happening on strings that can be parsed to a date to keep the semantic meaning of the date value.
