### ISSUE TITLE
When Appcues's js file is blocked, calls to analytics.page, identify etc. throw an exception

### ISSUE THREAD

**Issue by vinu-ally** [segmentio/analytics.js#624]
If Appcues destination is enabled and when the user loads the page in a browser, analytics.js tries to load the related Appcues's js file. If the load does not succeed (for ex: blocked in chrome dev tools), calls to analytics.identify, page etc. throws the following error:
TypeError: Cannot read property 'page' of undefined
TypeError: Cannot read property 'identify' of undefined

Expectation:
To gracefully handle if destination is not available.

**Comment by rmariuzzo** [comment]
I can see something similar too.

**Comment by paulparton** [comment]
https://github.com/segmentio/analytics.js/issues/627 Same issue?
