### ISSUE TITLE
Possible to check response object after a call to track?

### ISSUE THREAD

**Issue by boblauer** [segmentio/analytics.js#625]
I'm looking in my browser dev tools network tab, and when a `track` request is made with my ad blocker on, the response shows as a 200 but the body is empty. With the ad blocker off, the response body is `{ success: true }`.

I'm wondering if it's currently possible to access the respond body in code? I tried adding a callback to the `track` call, but it wasn't passed any parameters.

Is there an event I can listen to or some other way to access the response body to determine if an ad blocker intercepted the request?

**Comment by pooyaj** [comment]
@boblauer currently there is no way to subscribe to the track/etc. call responses.
