### ISSUE TITLE
Question: How can I provide a default property value (appVersion) to be included in every .track call?

### ISSUE THREAD

**Issue by aguynamedben** [segmentio/analytics.js#628]
Hi, we use Segment + analytics.js to send data to Mixpanel. We want to send `appVersion` as a property with every .track call so we can breakout events by `appVersion` in Mixpanel.

Here's what we did for now:

```js
analytics.track({
  event: 'Launch Result',
  properties: {
    appVersion: getAppVersion(),
  },
});
```

This works, but it's annoying because we have to remember to include the appVersion property in all the places we call .track.

Is there a way we can set appVersion as a defaultTrackProperty to be sent with every call to .track?

```js
analytics.defaultTrackProperties = { appVersion: getAppVersion() };
```

or during .identify?

```js
analytics.identify({
  userId: id,
  defaultTrackProperties: {
    appVersion: getAppVersion(),
  },
});
```

The other option we have is wrapping access to analytics.track within another function we manage, but you provide such a nice, usable API that I don't want to add a layer of muck top of it!

**Comment by pooyaj** [comment]
@aguynamedben we recently released a feature called Middleware that solves your problem. You probably need either a source middleware ( if need to add `appVersions` to all destinations ) or a destination middleware specifically for Mixpanel. You can check out the docs on Middleware here: 
https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/#middleware
