### ISSUE TITLE
How to remove chrome warning for new SameSite cookie policy

### ISSUE THREAD

**Issue by lpepin-sama** [segmentio/analytics.js#629]
I am getting a warning in the browser console when using the new Chrome (v80) regarding their new cookie security policy (https://blog.chromium.org/2020/02/samesite-cookie-changes-in-february.html). It seems like Segment cookies should be configured with SameSite=None;Secure in order to continue working.

If this is something we can fix ourselves, could a section be added in the Segment documentation showing us how?

If not, will this be fixed in a future version of Segment?

Thank you

**Comment by pooyaj** [comment]
This is now fixed. Just a note that there might be few cookie warning related to third party destinations, that is out of our control.

**Comment by untra** [comment]
so this is fixed... how? Will consumers have to update their[analytics snippet](https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/quickstart/) , or is there a new version of the analytics.js being percolated across CDN?

**Comment by kretz** [comment]
I'm still seeing the warning. 

```
A cookie associated with a cross-site resource at http://segment.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
```

Is there a specific release this is fixed in, or am I maybe missing something?

Thanks

**Comment by pooyaj** [comment]
@kretz This is fixed here: https://github.com/segmentio/analytics.js-core/pull/128. If using the CDN version of `analytics.js` you should be getting the fix without upgrading. If using `npm`, upgrade to the latest `analytics.js-core`. Also sometime you have Segment related cookies set prior to the fix, so also try clearing the cookies to see if it fixes the warning.
