### ISSUE TITLE
Add Typescript support, npm usage?

### ISSUE THREAD

**Issue by danawoodman** [segmentio/analytics.js#631]
### Typescript support?

Is there plans to support Typescript in this repo? Right now the only info I can find about Typescript is this React starter repo and it is tell me to do this:

```ts
declare global {
  interface Window { analytics: any; }
}
```

This is pretty unfortunate honestly as it doesn't help Typescript users at all. Seems like support for TS would be a very appreciated feature for developers?

### Importing as npm module?

Also, I cannot for the life of me find a way to use this repo without a global code snippet. It seems weird to me a tool like this has no way of using it via a standard `import`. I would expect something like:

```ts
import Analytics from 'analytics'

const analytics = new Analytics(SEGMENT_KEY)

analytics.track(...)
```

Can I do this? If not, why not?

Sorry for the two separate issues in one ticket but I think they're related somewhat.

**Comment by pooyaj** [comment]
@danawoodman Typescript is in the works, and can track the progress in [analytics.js-core](https://github.com/segmentio/analytics.js-core). The recommended way to use Segment is to use our CDN to get a custom bundle containing only the needed integrations + your settings. But we are working on documenting an alternative approach using our `npm` packages. Can check this repo for an example: https://github.com/segmentio/ajs-multiple-writekeys-demo

**Comment by pooyaj** [comment]
Update on this, we included the type definitions in the `analytics.js-core` library. Please check out the [Readme](https://github.com/visionmedia/debug) for instructions to use types. Also we are in the process of migrating the library to have full typescript coverage.

**Comment by joelpoloney** [comment]
@pooyaj I'm not sure what that Readme link is for but can we update the Readme in this repo to better document how to load the library via npm instead of through <script> tags?

**Comment by pooyaj** [comment]
@joelpoloney we don't recommend using this particular `analytics.js` repo as an npm module since this repo is outdated. If you like to use Segment as an npm instead of the <script> tag, we just added instructions here: https://github.com/segmentio/analytics.js-core#using-as-a-standalone-npm-package

**Comment by joelpoloney** [comment]
@pooyaj awesome, thank you for sharing that! We're on a TypeScript project and it appears there are still some issues with your types. Specifically:

1. `@segment/analytics.js-integration-segmentio` has no declaration file.
2. Analytics has an empty declaration file: 
  Type 'typeof import("<snip>/node_modules/@segment/analytics.js-core/build/analytics")' has no construct signatures.

I tried `import SegmentAnalytics from '@segment/analytics.js-core'` but there's no constructor on `SegmentAnalytics.AnalyticsJS`.

Not sure how to proceed. Perhaps it's just not ready for TypeScript yet, and if that's the case, that's fine.

Thanks!

**Comment by pooyaj** [comment]
@joelpoloney ah, good catch. We need to fix the types on `@segment/analytics.js-core/build/analytics`, should be relatively easy on our side, I'll open a ticket internally to fix this. As for `@segment/analytics.js-integration-segmentio` declarations, that will probably won't happen soon, as the https://github.com/segmentio/analytics.js-integrations repo doesn't have Typescript support yet, so adding type defs would be a bigger undertaking.

**Comment by joelpoloney** [comment]
Ok no worries. I can always declare the module in my own type definitions at least and then follow an issue to remove them once types are shipped with it. Will you post back to this issue when types are updated for the core library? Thank you!! 🙏

**Comment by pooyaj** [comment]
Awesome, yes, will keep this thread updated.
