### ISSUE TITLE
Opposite function of analytics.load()

### ISSUE THREAD

**Issue by arvinsim** [segmentio/analytics.js#645]
So I have a use case where I have to disable Segment based on some user data that is retrieved when the user is logged in.

I am using `create-react-app` and the initialized `window.analytics.load` is in the root `index.html`. As such, I could not do the check there to prevent Segment from loading.

Is there an `unload` function that does the opposite of `analytics.load` function? That is, I want to disable Segment or at least prevent it from sending information to destinations.

**Comment by kaustubh-smartBear** [comment]
possible workaround: Add a util for all your segments tracks, and add logic to send/prevent segment calls based on user property.

**Comment by arvinsim** [comment]
@kaustubh-smartBear I view that as a last resort since that means refactoring all our segment calls. It becomes a pretty big task.

**Comment by kaustubh-smartBear** [comment]
@arvinsim I agree. As a rule, I always use a util for any third party integrations. This makes a lot of things much easier as you never know what might change in the future.

**Comment by pooyaj** [comment]
@arvinsim There is no unload method. But probably the best bet is to use a sourceMiddlware that conditionally blocks the calls from passing trough ( by not calling the `next()` method ), or settings all the `integrations` to false. Check out the docs here: https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/middleware/#using-source-middlewares
