### ISSUE TITLE
clarification: multiple calls to identify for same userId?

### ISSUE THREAD

**Issue by mdaniel** [segmentio/analytics.js#65]
In the [docs for identify](https://segment.io/docs/methods/identify) I am unable to find any guidance for whether the method should be called once per userId (ever) or whether it is safe -- or even advisable -- to call it anytime a userId authenticates.

In a similar vein, if one calls identify multiple times for the same userId, but provides extra traits for the userId beyond those used on the first call, does that cause segment.io to view the userId as a new one?

**Comment by Kalyse** [comment]
I think you might have changed your docs on this point. 

It was ambiguous for me also. This issue provided clarification.
