### ISSUE TITLE
Google analytics.js confusion

### ISSUE THREAD

**Issue by mollerhoj** [segmentio/analytics.js#655]
Just trying to understand this space. I find it strange that there is apparently another lib called analytics.js that google hosts:
https://www.google-analytics.com/analytics.js

Is this simply a name collision, or is this library a wrapper or superset of google's analytics library?
I'm aware that one could use segment to send data to google analytics, I just find it strange that segment would choose a name for their library that overlaps 100% with a competing library? Is there a historic reason for this? Have I misunderstood something?

**Comment by richardscarrott** [comment]
@mollerhoj yeah it's a coincidence, they're not directly related; other than the fact that segment can optionally load in google analytics if you configure it as a destination in device mode.

**Comment by mollerhoj** [comment]
alright, thats unfortunate I guess. Thanks for the clarification :-)
