### ISSUE TITLE
Thoughts on GA custom variable (and w/ new Google analytics.js, custom dimensions/metrics)

### ISSUE THREAD

**Issue by drd** [segmentio/analytics.js#87]
I'm curious to see if anyone's thinking about or working on support for either classic ga.js custom variables or new-school Google analytics.js custom dimensions and metrics with analytics.js. So far I've thought about three ways of doing it:

1) Hijack identify() -- GA doesn't accept personally identifiable data so we ignore the identifier and parse out specific properties (slot, category, value, and scope).. custom vars are used to segment users so I think there is some logic to this

2) Hijack track() -- setting a custom variable doesn't match the semantics of track very well to me, so I like this less, but it's conceivable

3) Either add a separate method for the provider or do it entirely out-of-band -- the dirty feeling I get when I think about this makes me sad and is what led me to options 1 and 2.

I must admit I haven't spent a lot of time on this, but I don't currently see an answer to it w/ analytics.js and I wanted to see if it seems appropriate and within the scope of the project, or if I should just pursue another course.

**Comment by dmtintner** [comment]
Any updates on this? From what I understand there's still no way to use analytics.js with setCustomVar methods from piwik or GA. Is that correct?
